excluded:
  - .build
  - .swiftpm
  - dist
  - releases
  - Wiles.app

opt_in_rules:
  - force_unwrapping
  - implicitly_unwrapped_optional
  - closure_spacing
  - empty_count
  - fatal_error_message
  - first_where
  - overridden_super_call
  - redundant_nil_coalescing
  - toggle_bool
  - weak_delegate
  - prefer_self_in_static_references
  - yoda_condition
  - modifier_order
  - attributes
  - explicit_init
  - array_init
  - last_where
  - contains_over_first_not_nil
  - redundant_type_annotation

analyzer_rules:
  - unused_declaration
  - unused_import

line_length:
  warning: 180
  error: 180

type_body_length:
  warning: 400
  error: 600

file_length:
  warning: 500
  error: 800

function_body_length:
  warning: 40
  error: 80

cyclomatic_complexity:
  warning: 16
  error: 25

identifier_name:
  min_length:
    warning: 2
  excluded:
    - id
    - x
    - y
    - i
    - j
    - di
    - dj
    - dx
    - dy

attributes:
  always_on_same_line:
    - "@IBAction"
    - "@NSManaged"
  always_on_line_above:
    - "@available"

modifier_order:
  preferred_modifier_order:
    - override
    - acl
    - setterACL
    - dynamic
    - mutators
    - lazy
    - final
    - required
    - convenience
    - typeMethods
    - owned

trailing_whitespace:
  ignores_empty_lines: true

vertical_whitespace:
  max_empty_lines: 1

nesting:
  type_level:
    warning: 3
    error: 3
  function_level:
    warning: 3
    error: 3
