import SwiftUI
import AppKit

@main
struct WilesApp: App {
    @State private var appState = AppState()
    @Environment(\.openWindow) private var openWindow
    @Environment(\.openSettings) private var openSettings

    init() {
        NSApplication.shared.setActivationPolicy(.regular)
        NSApplication.shared.activate(ignoringOtherApps: true)
        NSWindow.allowsAutomaticWindowTabbing = false
    }

    var body: some Scene {
        WindowGroup(AppConstants.appName, id: AppConstants.mainWindowID) {
            MainContentView(appState: appState)
                .preferredColorScheme(appState.preferences.appAppearance.colorScheme)
                .sheet(item: $appState.propertiesItem) { item in
                    FilePropertiesSheet(item: item, appState: appState)
                }
                .sheet(isPresented: $appState.showNewFolderSheet) {
                    NewFolderSheet(appState: appState)
                }
                .sheet(isPresented: $appState.modal.showHelpSheet) {
                    HelpSheet(appState: appState)
                }
                .sheet(isPresented: $appState.modal.showAboutSheet) {
                    AboutSheet(appState: appState)
                }
                .sheet(isPresented: $appState.showAutoOrganizationSheet) {
                    AutoOrganizationSheet(appState: appState)
                }
                .sheet(isPresented: $appState.showHttpShareSheet) {
                    if let url = appState.httpShareFolderURL {
                        HttpShareSheet(appState: appState, folderURL: url)
                    }
                }
                .onAppear {
                    NSApplication.shared.activate(ignoringOtherApps: true)
                    let iconURL = Bundle.main.url(forResource: "AppIcon", withExtension: "png") ??
                                  Bundle.main.resourceURL?.appendingPathComponent("Wiles_Wiles.bundle/AppIcon.png") ??
                                  Bundle.main.bundleURL.appendingPathComponent("Wiles_Wiles.bundle/AppIcon.png")

                    if let iconImage = NSImage(contentsOf: iconURL) {
                        NSApplication.shared.applicationIconImage = iconImage
                    }
                    // `appState` is shared by every window — every sheet/overlay toggle on it
                    // (including `showShortcutsHUD`) shows in every open window at once. A
                    // per-window `@FocusedValue` scoping attempt for just the shortcuts HUD was
                    // tried and reverted (broke the shortcut entirely — `.focusedValue` needs an
                    // actual SwiftUI-focused control, which this app doesn't use). Revisit this for
                    // every affected sheet at once, properly, rather than one at a time — tracked as
                    // a TODO. `isRestorable = false` keeps each launch starting clean instead of
                    // macOS silently restoring however many windows were open at last quit.
                    for window in NSApplication.shared.windows {
                        window.tabbingMode = .disallowed
                        window.isMovableByWindowBackground = false
                        window.setFrameAutosaveName("WilesMainWindow")
                        window.isRestorable = false
                    }
                    if !CommandLine.arguments.contains("--ui-testing") {
                        PermissionService.requestInitialPermissions(language: appState.preferences.appLanguage)
                    }
                    appState.refreshCurrentDirectory()
                    AutoOrganizationService.shared.startMonitoring()
                }
        }
        .windowStyle(.hiddenTitleBar)
        .commands {
            appMenuCommands
            fileMenuCommands
            editMenuCommands
            viewMenuCommands
            CommandMenu(appState.tr(.goMenuTitle)) { goMenuCommands }
            CommandMenu(appState.tr(.toolsMenuTitle)) { toolsMenuCommands }
            helpMenuCommands
        }

        Settings {
            SettingsView(appState: appState)
        }
    }

    @CommandsBuilder private var appMenuCommands: some Commands {
        CommandGroup(replacing: .appInfo) {
            Button(appState.tr(.aboutWiles)) { appState.modal.showAboutSheet = true }
        }
        CommandGroup(replacing: .appSettings) {
            Button { openSettings() } label: {
                Label(appState.tr(.settingsMenuItem), systemImage: "gearshape")
            }
            .keyboardShortcut(",", modifiers: .command)
        }
    }

    @CommandsBuilder private var fileMenuCommands: some Commands {
        // SwiftUI's automatic "New Window" command is generated by AppKit from the OS locale, not
        // `appState.preferences.appLanguage` — it never respects the in-app language switcher.
        // Replacing `.newItem` gives full, translated control over it (see UI_TEST_BACKLOG.md).
        CommandGroup(replacing: .newItem) {
            // `appState` is a single instance shared by every window — every sheet/overlay flag on
            // it (including `showShortcutsHUD`) shows in every open window at once. Real per-window
            // isolation needs a follow-up (tracked as a TODO), not attempted here.
            Button(appState.tr(.newWindow)) { openWindow(id: AppConstants.mainWindowID) }
                .keyboardShortcut("n", modifiers: .command)
        }
        // Same story for "Close": it has no dedicated CommandGroupPlacement, so it rides along
        // inside `.saveItem` (the only remaining File-menu placement for non-document scenes).
        CommandGroup(replacing: .saveItem) {
            Button(appState.tr(.close)) { NSApplication.shared.keyWindow?.performClose(nil) }
                .keyboardShortcut("w", modifiers: .command)
        }
        CommandGroup(after: .newItem) {
            Button(appState.tr(.newFolder)) { appState.showNewFolderSheet = true }
                .keyboardShortcut("n", modifiers: [.command, .shift])
            Divider()
            Button(appState.tr(.open)) { appState.openSelectedItem() }
                .keyboardShortcut("o", modifiers: .command)
                .disabled(appState.selectedURLs.isEmpty)
            Button(appState.tr(.properties)) { appState.openPropertiesForSelected() }
                .keyboardShortcut("i", modifiers: .command)
                .disabled(appState.selectedURLs.isEmpty)
            Button(appState.tr(.quickLook)) { appState.triggerQuickLookForSelected() }
                .keyboardShortcut(" ", modifiers: [])
                .disabled(appState.selectedURLs.isEmpty)
            Divider()
            Button(appState.tr(.moveToTrash)) { appState.deleteSelected() }
                .disabled(appState.selectedURLs.isEmpty)
        }
    }

    @CommandsBuilder private var editMenuCommands: some Commands {
        CommandGroup(replacing: .undoRedo) {
            Button(appState.tr(.undo)) { appState.undoLastAction() }
                .keyboardShortcut("z", modifiers: .command)
            Button(appState.tr(.redo)) { appState.redoLastAction() }
                .keyboardShortcut("z", modifiers: [.command, .shift])
        }
        CommandGroup(replacing: .pasteboard) {
            Button(appState.tr(.cut)) { appState.cutSelected() }
                .keyboardShortcut("x", modifiers: .command)
                .disabled(appState.selectedURLs.isEmpty)
            Button(appState.tr(.copy)) { appState.copySelected() }
                .keyboardShortcut("c", modifiers: .command)
                .disabled(appState.selectedURLs.isEmpty)
            Button(appState.tr(.paste)) { appState.pasteToCurrentDirectory() }
                .keyboardShortcut("v", modifiers: .command)
            Divider()
            Button(appState.tr(.selectAll)) { appState.selectAllItems() }
                .keyboardShortcut("a", modifiers: .command)
            Divider()
            Button(appState.tr(.find)) { appState.toggleSearching() }
                .keyboardShortcut("f", modifiers: .command)
        }
    }

    // Everyday, frequently-toggled panels/actions stay here for quick keyboard access. Lower-
    // frequency display preferences (hidden files, tags, compact density, sidebar sections/mode)
    // moved into the new `Settings` scene (⌘,) — see `Views/Settings/*.swift` — to declutter the
    // menu bar per the redesign; those bindings still live on the same `PreferencesStore`, so
    // toggling them in Settings updates the UI live with zero behavior change.
    @CommandsBuilder private var viewMenuCommands: some Commands {
        CommandGroup(after: .sidebar) {
            Divider()
            Button(appState.tr(.shortcutsCheatsheetTitle)) {
                withAnimation(MotionTokens.snappySpring) {
                    appState.showShortcutsHUD.toggle()
                }
            }
            .keyboardShortcut(KeyboardShortcut("/", modifiers: .command, localization: .custom))
            Toggle(appState.tr(appState.preferences.showTerminalDrawer ? .hideTerminal : .showTerminal), isOn: $appState.preferences.showTerminalDrawer)
                .keyboardShortcut("j", modifiers: .command)
            Toggle(appState.tr(appState.preferences.showPreviewSidebar ? .hidePreview : .showPreviewSidebar), isOn: $appState.preferences.showPreviewSidebar)
                .keyboardShortcut("p", modifiers: [.command, .shift])
            Divider()
            Picker(selection: $appState.preferences.viewMode) {
                Text(appState.tr(.gridView)).tag(ViewMode.grid)
                Text(appState.tr(.listView)).tag(ViewMode.list)
                Text(appState.tr(.columnView)).tag(ViewMode.column)
            } label: {
                Label(appState.tr(.viewMode), systemImage: "square.grid.2x2")
            }
            Menu {
                Picker(appState.tr(.sortBy), selection: $appState.preferences.sortOption) {
                    ForEach(SortOption.allCases) { opt in Text(appState.tr(opt.l10nKey)).tag(opt) }
                }
                .onChange(of: appState.preferences.sortOption) { _, _ in appState.refreshCurrentDirectory() }
                Divider()
                Toggle(appState.tr(.ascending), isOn: $appState.preferences.sortAscending)
                    .onChange(of: appState.preferences.sortAscending) { _, _ in appState.refreshCurrentDirectory() }
            } label: {
                Label(appState.tr(.sortBy), systemImage: "arrow.up.arrow.down")
            }
        }
    }

    @ViewBuilder private var goMenuCommands: some View {
        Button(appState.tr(.back)) { appState.goBack() }
            .keyboardShortcut("[", modifiers: .command)
            .disabled(appState.navigation.historyBack.isEmpty)
        Button(appState.tr(.forward)) { appState.goForward() }
            .keyboardShortcut("]", modifiers: .command)
            .disabled(appState.navigation.historyForward.isEmpty)
        Button(appState.tr(.enclosingFolder)) { appState.goUp() }
        Divider()
        Button(appState.tr(.goToFolder)) { appState.startEditingPath() }
            .keyboardShortcut("l", modifiers: .command)
        Button(appState.tr(.connectToServer) + "...") { appState.showConnectToServerSheet = true }
            .keyboardShortcut("k", modifiers: .command)
    }

    @ViewBuilder private var toolsMenuCommands: some View {
        Button(appState.tr(.actDiskVisualizer) + "...") { appState.showDiskUsageSheet = true }
            .keyboardShortcut("d", modifiers: [.command, .shift])
        Button(appState.tr(.autoOrganization) + "...") { appState.showAutoOrganizationSheet = true }
        Divider()
        Menu(appState.tr(.copyPath)) {
            Button(appState.tr(.copyPathAbsolute)) {
                CopyPathService.copy(urls: [appState.navigation.currentURL], variant: .absolute)
            }
            Button(appState.tr(.copyPathRelative)) {
                CopyPathService.copy(urls: [appState.navigation.currentURL], variant: .relative, relativeTo: appState.navigation.currentURL.deletingLastPathComponent())
            }
            Button(appState.tr(.copyPathURL)) {
                CopyPathService.copy(urls: [appState.navigation.currentURL], variant: .fileURL)
            }
            Button(appState.tr(.copyPathTerminal)) {
                CopyPathService.copy(urls: [appState.navigation.currentURL], variant: .terminalEscaped)
            }
        }
        Divider()
        Button(appState.tr(.shortcutsCheatsheetTitle)) {
            withAnimation(MotionTokens.snappySpring) {
                appState.showShortcutsHUD.toggle()
            }
        }
        .keyboardShortcut(KeyboardShortcut("/", modifiers: .command, localization: .custom))
    }

    @CommandsBuilder private var helpMenuCommands: some Commands {
        CommandGroup(replacing: .help) {
            Button(appState.tr(.wilesHelpAndShortcuts)) { appState.modal.showHelpSheet = true }
                .keyboardShortcut("?", modifiers: .command)
        }
    }
}
