import AppKit
import SwiftUI

/// File menu: New Window/Close, plus per-selected-item actions (new folder/file, open,
/// properties, quick look, move to trash). Split out of `WilesApp.swift` — pure code motion, no
/// behavior change.
struct FileMenuCommands: LocalizedCommands {
    let sharedPreferences: PreferencesStore
    @Environment(\.openWindow)
    private var openWindow
    @FocusedValue(\.appState)
    private var appState
    @FocusedValue(\.windowUIState)
    private var windowUIState
    @FocusedValue(\.isTextFieldEditingActive)
    private var isTextFieldEditingActive

    /// While a text field owns focus, disable the plain-key destructive items (Space/Delete) so
    /// `NSMenu` can't fire their unmodified key equivalents mid-edit. See `MenuTextEditingState`.
    private var isEditingText: Bool {
        MenuTextEditingState.isActive(
            isTextFieldEditingActive: isTextFieldEditingActive,
            isSearching: appState?.selection.isSearching ?? false,
            liveFirstResponderIsText: NSApplication.shared.keyWindow?.firstResponder is NSText)
    }

    var body: some Commands {
        // SwiftUI's automatic "New Window" command is generated by AppKit from the OS locale, not
        // `appState.preferences.appearance.appLanguage` — it never respects the in-app language switcher.
        // Replacing `.newItem` gives full, translated control over it (see UI_TEST_BACKLOG.md).
        CommandGroup(replacing: .newItem) {
            Button(tr(.newWindow)) { openWindow(id: AppConstants.mainWindowID) }
                .keyboardShortcut(.newWindow)
        }
        // Same story for "Close": it has no dedicated CommandGroupPlacement, so it rides along
        // inside `.saveItem` (the only remaining File-menu placement for non-document scenes).
        CommandGroup(replacing: .saveItem) {
            Button(tr(.close)) { NSApplication.shared.keyWindow?.performClose(nil) }
                .keyboardShortcut(.closeWindow)
        }
        CommandGroup(after: .newItem) {
            fileItemActionCommands
        }
    }

    @ViewBuilder private var fileItemActionCommands: some View {
        if let appState, let windowUIState {
            Button(tr(.newFolder)) { appState.createNewFolderAndRename(windowUIState: windowUIState) }
                .keyboardShortcut(.newFolder)
            Button(tr(.newFileTitle)) { appState.createNewFileAndRename(windowUIState: windowUIState) }
                .keyboardShortcut(.newFile)
            Divider()
            Button(tr(.open)) { appState.openSelectedItem() }
                .keyboardShortcut(.open)
                .disabled(appState.selection.selectedURLs.isEmpty)
            Button(tr(.properties)) { appState.openPropertiesForSelected(windowUIState: windowUIState) }
                .keyboardShortcut(.properties)
                .disabled(appState.selection.selectedURLs.isEmpty)
            Button(tr(.quickLook)) { appState.triggerQuickLookForSelected(windowUIState: windowUIState) }
                .keyboardShortcut(.quickLook)
                .disabled(isQuickLookDisabled)
            Divider()
            // `.disabled` while the terminal is focused so the plain Space / Delete menu key
            // equivalents can't fire from terminal input, and while any text field owns focus
            // so Backspace mid-rename can't Trash the file.
            Button(tr(.moveToTrash)) { appState.deleteSelected(windowUIState: windowUIState) }
                .keyboardShortcut(.moveToTrash)
                .disabled(isMoveToTrashDisabled)
        }
    }

    /// Space fires Quick Look; disabled with no selection, while the terminal is focused, or while
    /// a text field is being edited (a filename with a space would otherwise open the panel).
    private var isQuickLookDisabled: Bool {
        guard let appState, let windowUIState else { return true }
        return appState.selection.selectedURLs.isEmpty || windowUIState.isTerminalFocused || isEditingText
    }

    /// Delete/Backspace fires Move to Trash; disabled with no selection, while the terminal is
    /// focused, or while a text field is being edited (Backspace mid-rename must not Trash the file).
    private var isMoveToTrashDisabled: Bool {
        guard let appState, let windowUIState else { return true }
        return appState.selection.selectedURLs.isEmpty || windowUIState.isTerminalFocused || isEditingText
    }
}
