import AppKit
import SwiftUI

/// File menu: New Window/Close, plus per-selected-item actions (new folder/file, open,
/// properties, quick look, move to trash). Split out of `WilesApp.swift` — pure code motion, no
/// behavior change.
struct FileMenuCommands: Commands {
    let sharedPreferences: PreferencesStore
    @Environment(\.openWindow)
    private var openWindow
    @FocusedValue(\.appState)
    private var appState
    @FocusedValue(\.windowUIState)
    private var windowUIState

    private func tr(_ key: L10n.Key) -> String {
        L10n.string(key, lang: sharedPreferences.appLanguage)
    }

    var body: some Commands {
        // SwiftUI's automatic "New Window" command is generated by AppKit from the OS locale, not
        // `appState.preferences.appLanguage` — it never respects the in-app language switcher.
        // Replacing `.newItem` gives full, translated control over it (see UI_TEST_BACKLOG.md).
        CommandGroup(replacing: .newItem) {
            Button(tr(.newWindow)) { openWindow(id: AppConstants.mainWindowID) }
                .keyboardShortcut("n", modifiers: .command)
        }
        // Same story for "Close": it has no dedicated CommandGroupPlacement, so it rides along
        // inside `.saveItem` (the only remaining File-menu placement for non-document scenes).
        CommandGroup(replacing: .saveItem) {
            Button(tr(.close)) { NSApplication.shared.keyWindow?.performClose(nil) }
                .keyboardShortcut("w", modifiers: .command)
        }
        CommandGroup(after: .newItem) {
            fileItemActionCommands
        }
    }

    @ViewBuilder private var fileItemActionCommands: some View {
        if let appState, let windowUIState {
            Button(tr(.newFolder)) { appState.createNewFolderAndRename(windowUIState: windowUIState) }
                .keyboardShortcut("n", modifiers: [.command, .shift])
            Button(tr(.newFileTitle)) { appState.createNewFileAndRename(windowUIState: windowUIState) }
            Divider()
            Button(tr(.open)) { appState.openSelectedItem() }
                .keyboardShortcut("o", modifiers: .command)
                .disabled(appState.selectedURLs.isEmpty)
            Button(tr(.properties)) { appState.openPropertiesForSelected(windowUIState: windowUIState) }
                .keyboardShortcut("i", modifiers: .command)
                .disabled(appState.selectedURLs.isEmpty)
            Button(tr(.quickLook)) { appState.triggerQuickLookForSelected(windowUIState: windowUIState) }
                .keyboardShortcut(" ", modifiers: [])
                .disabled(appState.selectedURLs.isEmpty)
            Divider()
            Button(tr(.moveToTrash)) { appState.deleteSelected(windowUIState: windowUIState) }
                .disabled(appState.selectedURLs.isEmpty)
        }
    }
}
