import Foundation

extension L10n {
    static let de: [Key: String] = [
        .newFolder: "Neuer Ordner...",
        .paste: "Einfügen",
        .selectAll: "Alles auswählen",
        .sortBy: "Sortieren nach",
        .viewMode: "Ansichtsmodus",
        .gridView: "Rasteransicht",
        .listView: "Listenansicht",
        .showHiddenFiles: "Ausgeblendete Dateien anzeigen",
        .showHiddenFilesGnome: "Ausgeblendete Dateien anzeigen (Ctrl+H)",
        .showHiddenFilesMac: "Ausgeblendete Dateien anzeigen (Cmd+Shift+.)",
        .hideStatusBar: "Statusleiste ausblenden",
        .showStatusBar: "Statusleiste anzeigen",
        .showFavorites: "Favoriten anzeigen",
        .showMacSection: "MAC-Bereich anzeigen",
        .showRecents: "Zuletzt verwendet anzeigen",
        .showPlaces: "Orte anzeigen",
        .showSidebarSectionTitles: "Seitenleisten-Titel anzeigen",
        .sidebarMode: "Sidebar-Modus",
        .places: "Orte & Geräte",
        .shortcutMode: "Tastenkürzel-Modus",
        .refresh: "Aktualisieren",
        .copyPath: "Pfad kopieren",
        .copyPathAbsolute: "Absoluter Pfad",
        .copyPathRelative: "Relativer Pfad",
        .copyPathURL: "Datei-URL (file://)",
        .copyPathTerminal: "Terminal-Pfad (maskiert)",
        .folderProperties: "Ordnereigenschaften",
        .open: "Öffnen",
        .quickLook: "Übersicht",
        .removeFromFavorites: "Aus Favoriten entfernen",
        .addToFavorites: "Zu Favoriten hinzufügen",
        .cut: "Ausschneiden",
        .copy: "Kopieren",
        .copyContent: "Inhalt kopieren",
        .moveToTrash: "In den Papierkorb legen",
        .compressToZip: "In ZIP komprimieren",
        .extractHere: "Archiv hier entpacken",
        .rename: "Umbenennen...",
        .properties: "Eigenschaften",
        .noResultsFound: "Keine Ergebnisse gefunden",
        .folderIsEmpty: "Ordner ist leer",
        .name: "Name",
        .size: "Größe",
        .dateModified: "Änderungsdatum",
        .kind: "Art",
        .folder: "Ordner",
        .favorites: "FAVORITEN",
        .mac: "MAC",
        .recents: "ZULETZT VERWENDET",
        .devices: "GERÄTE",
        .directoryTree: "VERZEICHNISBAUM",
        .searchPlaceholder: "Suchen in",
        .home: "Benutzerordner",
        .desktop: "Schreibtisch",
        .documents: "Dokumente",
        .downloads: "Downloads",
        .music: "Musik",
        .pictures: "Bilder",
        .movies: "Filme",
        .trash: "Papierkorb",
        .applications: "Programme",
        .airDrop: "AirDrop",
        .iCloudDrive: "iCloud Drive",
        .freeSpace: "frei",
        .language: "Sprache",
        .cancel: "Abbrechen",
        .create: "Erstellen",
        .createNewFolder: "Neuen Ordner erstellen",
        .folderNamePlaceholder: "Ordnername",
        .defaultFolderName: "Neuer Ordner",
        .enterPathPlaceholder: "Pfad eingeben...",
        .root: "Stammverzeichnis",
        .ascending: "Aufsteigend",
        .location: "Ort",
        .modified: "Geändert",
        .hidden: "Ausgeblendete",
        .yes: "Ja",
        .no: "Nein",
        .close: "Schließen",
        .parentFolder: "Übergeordneter Ordner",
        .done: "Fertig",
        .helpShortcuts: "Hilfe & Tastenkürzel",
        .batchRename: "Stapelumbenennung",
        .find: "Suchen",
        .replaceWith: "Ersetzen durch",
        .prefix: "Präfix",
        .suffix: "Suffix",
        .sequenceNumbering: "Fortlaufende Nummerierung",
        .startNumber: "Startnummer",
        .preview: "Vorschau",
        .originalName: "Originalname",
        .newName: "Neuer Name",
        .apply: "Anwenden",
        .quickConvertImage: "Schnelle Bildkonvertierung...",
        .targetFormat: "Zielformat",
        .resizePreset: "Bildgröße",
        .cropPreset: "Seitenverhältnis zuschneiden",
        .quality: "Qualität",
        .convert: "Konvertieren",
        .diskUsageVisualizer: "Speicherplatz-Visualisierung",
        .topLargestItems: "Größte Elemente",
        .aboutWiles: "Über Wiles",
        .aboutDescription: "Ein nativer macOS-Dateimanager, sehr schnell und entwickelt, um das Beste aus GNOME Files und Finder zu vereinen.",
        .createdBy: "Erstellt von Marco PS",
        .version: "Version",
        .translucentLevel: "Transparenz",
        .sidebarTranslucentLevel: "Seitenleisten-Transparenz",
        .contentTranslucentLevel: "Inhalts-Transparenz",
        .showPreviewSidebar: "Vorschau anzeigen",
        .moreInfo: "Mehr Info...",
        .general: "Allgemein",
        .permissions: "Freigabe & Zugriffsrechte",
        .owner: "Eigentümer",
        .group: "Gruppe",
        .created: "Erstellt",
        .lastOpened: "Zuletzt geöffnet",
        .dimensions: "Abmessungen",
        .duration: "Dauer",
        .fetchError: "Eigenschaften konnten nicht geladen werden.",
        .newFileTitle: "Neue Datei",
        .selectTemplate: "Vorlage Auswählen",
        .fileNameLabel: "Dateiname",
        .extractArchive: "Archiv Entpacken",
        .connectToServer: "Mit Server Verbinden",
        .connect: "Verbinden",
        .showTags: "Tags anzeigen",
        .tags: "Tags",
        .red: "Rot",
        .orange: "Orange",
        .yellow: "Gelb",
        .green: "Grün",
        .blue: "Blau",
        .purple: "Lila",
        .gray: "Grau",
        .clearAllTags: "Alle Tags löschen",
        .services: "Dienste",
        .compactDensity: "Kompakte Dichte-Layout",
        .helpGuideTitle: "Hilfe & Funktionshandbuch",
        .tabOverview: "Übersicht",
        .tabFeatures: "Funktionen & Werkzeuge",
        .tabSystem: "Navigation & System",
        .tabShortcuts: "Tastaturkurzbefehle",
        .overviewDesc: "Wiles ist ein leistungsstarker, nativer macOS-Dateimanager.",
        .domainToolsTitle: "Domänenwerkzeuge & Highlights",
        .helpTagsTitle: "Native macOS-Tags & Filterung",
        .helpTagsDesc: "Aktivieren Sie 'Tags anzeigen' im Menü Ansicht.",
        .helpTerminalTitle: "Im Terminal öffnen",
        .helpTerminalDesc: "Rechtsklick auf einen Ordner -> 'Im Terminal öffnen'.",
        .helpZipTitle: "ZIP-Archiv-Komprimierung & Extraktion",
        .helpZipDesc: "Rechtsklick -> 'In ZIP komprimieren' oder 'Hier entpacken'.",
        .helpDiskTitle: "Speicherplatz-Visualisierung",
        .helpDiskDesc: "Drücken Sie Umschalt+Cmd+D, um große Dateien zu untersuchen.",
        .helpImageTitle: "Schneller Bildkonverter",
        .helpImageDesc: "Rechtsklick auf ein Bild -> 'Schnelles Konvertieren des Bildes...'.",
        .helpBatchTitle: "Stapel-Umbenennungswerkzeug",
        .helpBatchDesc: "Wählen Sie mehrere Dateien aus und drücken Sie F2.",
        .helpSymlinkTitle: "Erstellung Symbolischer Links",
        .helpSymlinkDesc: "Rechtsklick -> 'Symbolischen Link erstellen...'.",
        .helpTemplateTitle: "Neue Dateivorlagen",
        .helpTemplateDesc: "Rechtsklick auf den Hintergrund -> 'Neue Datei...'.",
        .helpCopyContentTitle: "Dateiinhalt in die Zwischenablage kopieren",
        .helpCopyContentDesc: "Rechtsklick -> 'Inhalt kopieren'.",
        .helpShredTitle: "Sicherer Datei-Schredder",
        .helpShredDesc: "Rechtsklick -> 'Datei sicher schreddern...'.",
        .helpServerTitle: "Mit Netzwerkserver verbinden",
        .helpWifiShareTitle: "WLAN-Freigabe",
        .helpWifiShareDesc: "Teilen Sie jeden Ordner sofort über Ihr lokales Netzwerk per HTTP.",
        .helpAutoOrgTitle: "Automatische Organisation",
        .helpAutoOrgDesc: "Erstellen Sie Regeln, um eingehende Dateien automatisch in bestimmte Ordner zu verschieben.",
        .helpServerDesc: "Drücken Sie Cmd+K, um eine Verbindung zu einem Netzwerkserver herzustellen.",
        .navSystemTitle: "Navigation, System & Anpassung",
        .helpUndoTitle: "Vollständige Rückgängig / Wiederholen Engine",
        .helpUndoDesc: "Drücken Sie Cmd+Z zum Rückgängigmachen oder Cmd+Shift+Z zum Wiederholen.",
        .helpPreviewTitle: "Vorschau-Seitenleiste mit Syntax-Hervorhebung",
        .helpPreviewDesc: "Drücken Sie Umschalt+Cmd+P für die Vorschau-Seitenleiste.",
        .helpViewModeMemoryTitle: "Ansichtsmodus-Speicher pro Verzeichnis",
        .helpViewModeMemoryDesc: "Wiles merkt sich den bevorzugten Ansichtsmodus für jeden Ordner.",
        .helpPathBarTitle: "Interaktive Pfadleiste",
        .helpPathBarDesc: "Klicken Sie auf ein Segment, um zu navigieren.",
        .helpDragDropTitle: "Drag & Drop Dateivorgänge",
        .helpDragDropDesc: "Ziehen Sie Dateien in Favoriten oder Ordner.",
        .helpI18nTitle: "Mehrsprachiges System (i18n)",
        .helpI18nDesc: "Automatische Erkennung der System-Sprache mit manueller Wahl.",
        .helpTranslucentTitle: "Transparenter Hintergrund & Dichte-Einstellungen",
        .helpTranslucentDesc: "Passen Sie die Transparenz und die kompakte Dichte an.",
        .navProfilesTitle: "Navigations-Tastaturprofil",
        .gnomeModeTitle: "GNOME-Modus (Standard)",
        .gnomeModeDesc: "• Eingabe: Ordner öffnen\n• F2: Umbenennen\n• Rückschritt: Übergeordneter Ordner\n• Strg+H: Ausgeblendete Dateien",
        .macModeTitle: "macOS Finder-Modus",
        .macModeDesc: "• Cmd+Runter: Ordner öffnen\n• Eingabe: Umbenennen\n• Cmd+Hoch: Übergeordneter Ordner\n• Cmd+Shift+.: Ausgeblendete Dateien",
        .shortcutsCheatsheetTitle: "Tastaturkurzbefehle Übersicht",
        .actUndo: "Vorgang rückgängig machen",
        .actRedo: "Vorgang wiederholen",
        .actQuickLook: "Übersicht-Vorschau",
        .actTogglePreview: "Vorschau-Seitenleiste umschalten",
        .actToggleTerminal: "Integriertes Terminal umschalten",
        .actSearch: "Im Verzeichnis suchen",
        .networkAndCloud: "NETZWERK & CLOUD",
        .shareFolderWifi: "Ordner über WLAN freigeben",
        .autoOrganization: "Regeln für automatische Organisation...",
        .noAutoOrgRules: "Keine Regeln",
        .noAutoOrgRulesDesc: "Dateien bleiben, wo sie sind.",
        .addNewRule: "Neue Regel hinzufügen",
        .ifFileIn: "Wenn Datei in:",
        .selectFolder: "Ordner auswählen...",
        .ruleValuePlaceholder: "Wert (z.B. pdf)",
        .moveTo: "Verschieben nach:",
        .addRule: "Regel hinzufügen",
        .actDiskVisualizer: "Speicherplatz-Visualisierung",
        .actConnectServer: "Mit Server verbinden",
        .actNewFolderShortcut: "Neuer Ordner",
        .actItemProperties: "Element-Eigenschaften / Info",
        .actCopyShortcut: "Auswahl kopieren",
        .actCutShortcut: "Auswahl ausschneiden",
        .actPasteShortcut: "Dateien einfügen",
        .actMoveTrash: "In den Papierkorb verschieben",
        .actNavBackForward: "Zurück / Vorwärts navigieren",
        .actParentFolder: "Übergeordneter Ordner",
        .actRefreshShortcut: "Verzeichnis aktualisieren",
        .actToggleStatusBar: "Statusleiste umschalten",
        .fullDiskAccessPromptTitle: "Voller Festplattenzugriff",
        .fullDiskAccessPromptMessage: "Wiles benötigt vollen Festplattenzugriff, um alle Ordner ohne wiederholte Berechtigungsanfragen zu durchsuchen. Erteile ihn einmal in den Systemeinstellungen.",
        .openSystemSettings: "Systemeinstellungen öffnen",
        .notNow: "Nicht jetzt"
,
        .deleteImmediately: "Sofort löschen",
        .secureShred: "Datei sicher vernichten...",
        .createSymlink: "Symbolischen Link erstellen...",
        .compressToTarGz: "In .tar.gz komprimieren",
        .hideTerminal: "Terminal ausblenden",
        .showTerminal: "Terminal anzeigen",
        .hidePreview: "Vorschau ausblenden",
        .showNetworkAndCloud: "Netzwerk & Cloud anzeigen",
        .back: "Zurück",
        .forward: "Vorwärts",
        .goToFolder: "Gehe zum Ordner...",
        .filterImages: "Bilder filtern (kind:image)",
        .filterDocuments: "Dokumente filtern (kind:doc)",
        .filterCodeFiles: "Codedateien filtern (kind:code)",
        .filterFolders: "Ordner filtern (kind:folder)",
        .filterPDFs: "PDFs filtern (ext:pdf)",
        .filterLargeFiles: "Große Dateien filtern >10MB (size:>10m)",
        .filterModified7Days: "Geändert in den letzten 7 Tagen (date:7d)",
        .scanningFolderSize: "Ordnergröße scannen...",
        .backgroundOperations: "Hintergrundoperationen",
        .noActiveOperations: "Keine aktiven Operationen",
        .sharingActive: "Freigabe aktiv",
        .wifiShareNotice: "Jeder in Ihrem WLAN-Netzwerk kann über die obige Adresse auf diesen Ordner zugreifen.",
        .startingServer: "Server starten...",
        .linkType: "Link-Typ",
        .symlinkName: "Symbolischer Linkname",
        .noSelection: "Keine Auswahl",
        .codePreview: "Code-Vorschau"
,
        .openWith: "Öffnen mit",
        .selectOtherApp: "Anderes...",
        .downloadFromiCloud: "Aus iCloud herunterladen",
        .smartFolders: "INTELLIGENTE ORDNER",
        .saveSearch: "Suche speichern",
        .saveAsSmartFolder: "Als intelligenten Ordner speichern...",
        .smartFolderName: "Name des intelligenten Ordners",
        .sharingAndPermissions: "Freigabe & Rechte",
        .read: "Lesen",
        .write: "Schreiben",
        .execute: "Ausführen",
        .applyPermissions: "Rechte anwenden",
        .compressWithPassword: "Mit Passwort komprimieren...",
        .enterPassword: "Passwort eingeben",
        .password: "Passwort",
        .others: "Andere",
        .changeAllDefaultApp: "Immer öffnen mit",
        .recentServers: "Neueste Server",
        .mergeIntoPDF: "In eine Einzel-PDF zusammenführen",
        .camera: "Kamera",
        .lens: "Objektiv",
        .aperture: "Blende",
        .focalLength: "Brennweite",
        .dateTaken: "Aufnahmedatum",
        .searchScope: "Suchbereich",
        .searchByName: "Dateiname",
        .searchByContent: "Dateinhalt",
        .inspectArchive: "Archivinhalt prüfen...",
        .permissionDeniedNotice: "Zugriff verweigert: Wiles kann den Inhalt dieses Ordners nicht lesen."
,
        .emptyFolder: "Dieser Ordner ist leer",
        .clearSearch: "Suche löschen"
,
        .grantFullDiskAccess: "Vollzugriff auf die Festplatte gewähren (Alle Ordner)...",
        .fullDiskAccessNotice: "Gewähren Sie Vollzugriff auf die Festplatte in den Systemeinstellungen, um ohne wiederholte Abfragen auf alle Ordner zuzugreifen."
,
        .findDuplicates: "Doppelte Dateien suchen...",
        .duplicateCleanerTitle: "Doppelte Dateien Reiniger",
        .reclaimableSpace: "Rückgewinnbarer Speicherplatz",
        .trashSelectedDuplicates: "Ausgewählte Duplikate in den Papierkorb verschieben",
        .noDuplicatesFound: "Keine doppelten Dateien gefunden",
        .batchRenameTitle: "Stapelumbenennung von Dateien",
        .namingPattern: "Benennungsmuster",
        .regexReplace: "Regex-Muster",
        .emptyTrash: "Papierkorb leeren",
        .emptyTrashConfirm: "Möchten Sie wirklich alle Elemente im Papierkorb dauerhaft löschen?"
    ]
}
