import Foundation

extension L10n {
    static let polish: [Key: String] = [
        .undo: "Cofnij",
        .redo: "Ponów",
        .enclosingFolder: "Folder Nadrzędny",
        .wilesHelpAndShortcuts: "Pomoc i Skróty Wiles",
        .newFolder: "Nowy folder",
        .paste: "Wklej",
        .selectAll: "Zaznacz wszystko",
        .sortBy: "Sort By",
        .viewMode: "View Mode",
        .gridView: "Grid View",
        .listView: "List View",
        .showHiddenFiles: "Show Hidden Files",
        .showHiddenFilesGnome: "Show Hidden Files (Ctrl+H)",
        .showHiddenFilesMac: "Show Hidden Files (Cmd+Shift+.)",
        .hideStatusBar: "Hide Status Bar",
        .showStatusBar: "Show Status Bar",
        .showFavorites: "Show Favorites",
        .showMacSection: "Show MAC Section",
        .showRecents: "Show Recents",
        .showPlaces: "Pokaż Miejsca",
        .showSidebarSectionTitles: "Pokaż Tytuły Paska Bocznego",
        .sidebarMode: "Sidebar Mode",
        .places: "Places & Devices",
        .shortcutMode: "Shortcut Mode",
        .refresh: "Odśwież",
        .copyPath: "Kopiuj Ścieżkę",
        .copyPathAbsolute: "Ścieżka Bezwzględna",
        .copyPathRelative: "Ścieżka Względna",
        .copyPathURL: "URL Pliku (file://)",
        .copyPathTerminal: "Ścieżka Eskejpowana dla Terminala",
        .folderProperties: "Folder Properties",
        .open: "Otwórz",
        .quickLook: "Szybki podgląd",
        .removeFromFavorites: "Remove from Favorites",
        .addToFavorites: "Add to Favorites",
        .cut: "Wytnij",
        .copy: "Kopiuj",
        .copyContent: "Copy Content",
        .moveToTrash: "Move to Trash",
        .noSelection: "Brak Zaznaczenia",
        .codePreview: "Podgląd Kodu",
        .sharingActive: "Udostępnianie Aktywne",
        .createSymbolicLink: "Utwórz Dowiązanie Symboliczne",
        .linkType: "Typ Dowiązania",
        .symlinkNameLabel: "Nazwa Dowiązania",
        .createLink: "Utwórz Dowiązanie",
        .wilesFileManager: "Menedżer Plików Wiles",
        .backgroundOperations: "Operacje w Tle",
        .noActiveOperations: "Brak aktywnych operacji",
        .itemsSelectedSuffix: "wybranych elementów",
        .activeSuffix: "aktywnych",
        .compressToZip: "Compress to ZIP",
        .extractHere: "Extract Archive Here",
        .rename: "Zmień nazwę",
        .properties: "Informacje",
        .noResultsFound: "No Results Found",
        .folderIsEmpty: "Folder is Empty",
        .name: "Name",
        .size: "Size",
        .dateModified: "Date Modified",
        .kind: "Kind",
        .folder: "Folder",
        .favorites: "FAVORITES",
        .mac: "MAC",
        .recents: "RECENTS",
        .devices: "DEVICES",
        .directoryTree: "DIRECTORY TREE",
        .searchPlaceholder: "Search in",
        .home: "Katalog domowy",
        .desktop: "Biurko",
        .documents: "Dokumenty",
        .downloads: "Pobrane",
        .music: "Muzyka",
        .pictures: "Obrazki",
        .movies: "Filmy",
        .trash: "Kosz",
        .applications: "Aplikacje",
        .airDrop: "AirDrop",
        .iCloudDrive: "iCloud Drive",
        .freeSpace: "Wolne miejsce",
        .language: "Language",
        .cancel: "Anuluj",
        .create: "Utwórz",
        .createNewFolder: "Create New Folder",
        .folderNamePlaceholder: "Folder Name",
        .defaultFolderName: "New Folder",
        .enterPathPlaceholder: "Enter path...",
        .root: "Root",
        .ascending: "Ascending",
        .location: "Location",
        .modified: "Modified",
        .hidden: "Hidden",
        .yes: "Yes",
        .no: "No",
        .close: "Zamknij",
        .parentFolder: "Parent Folder",
        .done: "Done",
        .helpShortcuts: "Help & Shortcuts",
        .batchRename: "Batch Rename",
        .find: "Find",
        .replaceWith: "Replace With",
        .prefix: "Prefix",
        .suffix: "Suffix",
        .sequenceNumbering: "Sequence Numbering",
        .startNumber: "Start Number",
        .preview: "Preview",
        .originalName: "Original Name",
        .newName: "New Name",
        .apply: "Zastosuj",
        .quickConvertImage: "Quick Convert & Resize...",
        .targetFormat: "Target Format",
        .resizePreset: "Resize Preset",
        .cropPreset: "Aspect Ratio Crop",
        .quality: "Quality",
        .convert: "Convert",
        .diskUsageVisualizer: "Folder Disk Usage Visualizer",
        .topLargestItems: "Top Largest Items",
        .aboutWiles: "About Wiles",
        .aboutDescription: "A fast, native macOS file manager designed to bridge the best of GNOME Files (Nautilus) and macOS Finder.",
        .createdBy: "Created by Marco PS",
        .version: "Version",
        .translucentLevel: "Transparency",
        .sidebarTranslucentLevel: "Sidebar Translucency",
        .contentTranslucentLevel: "Content Translucency",
        .showPreviewSidebar: "Show Preview",
        .moreInfo: "More Info...",
        .general: "General",
        .permissions: "Sharing & Permissions",
        .owner: "Owner",
        .group: "Group",
        .created: "Created",
        .lastOpened: "Last Opened",
        .dimensions: "Dimensions",
        .duration: "Duration",
        .fetchError: "Unable to load properties.",
        .newFileTitle: "New File",
        .selectTemplate: "Select Template",
        .fileNameLabel: "File Name",
        .extractArchive: "Extract Archive",
        .connectToServer: "Connect to Server",
        .connect: "Connect",
        .showTags: "Show Tags",
        .tags: "Tags",
        .red: "Red",
        .orange: "Orange",
        .yellow: "Yellow",
        .green: "Green",
        .blue: "Blue",
        .purple: "Purple",
        .gray: "Gray",
        .clearAllTags: "Clear All Tags",
        .services: "Services",
        .compactDensity: "Compact Density Layout",
        .helpGuideTitle: "Help & Feature Guide",
        .tabOverview: "Overview",
        .tabFeatures: "Features & Tools",
        .tabSystem: "Navigation & System",
        .tabShortcuts: "Shortcuts",
        .overviewDesc:
            "Wiles is a high-performance, native macOS file manager built with Apple's AppKit and SwiftUI frameworks. " +
                "It seamlessly bridges GNOME Files (Nautilus) workflow efficiency with macOS Finder's power features.",
        .domainToolsTitle: "Domain Tools & Feature Highlights",
        .helpTagsTitle: "Native macOS Tags & Filtering",
        .helpTagsDesc: "Enable 'Show Tags' in View/Options menu. Right-click any file > Tags to color tag it. Click sidebar color tags or search 'tag:color' to filter.",
        .helpTerminalTitle: "Open in Terminal",
        .helpTerminalDesc: "Right-click any folder or empty background area -> 'Open in Terminal' to launch native Terminal directly at that directory.",
        .helpZipTitle: "ZIP Archive Compression & Extraction",
        .helpZipDesc: "Right-click selected files -> 'Compress to ZIP' or right-click any .zip file -> 'Extract Here' for background archive processing.",
        .helpDiskTitle: "Disk Space Visualizer",
        .helpDiskDesc: "Press Shift+Cmd+D or choose 'Disk Usage Visualizer...' from background menu to inspect largest files and folder size breakdowns.",
        .helpImageTitle: "Image Quick Converter",
        .helpImageDesc: "Right-click any image -> 'Quick Convert Image...' to batch convert (PNG, JPG, WEBP, HEIC), resize, or crop.",
        .helpBatchTitle: "Batch Rename Tool",
        .helpBatchDesc: "Select multiple files and press F2 (or Rename) to open Batch Rename with regex matching, prefix/suffix additions, and sequence numbers.",
        .helpSymlinkTitle: "Symbolic Link Creation",
        .helpSymlinkDesc: "Right-click any file or folder -> 'Create Symlink...' to generate relative or absolute symbolic links.",
        .helpTemplateTitle: "New File Templates",
        .helpTemplateDesc: "Right-click background -> 'New File...' to quickly generate empty text, markdown, code files, or custom templates.",
        .helpCopyContentTitle: "Copy File Content to Clipboard",
        .helpCopyContentDesc: "Right-click text/data files -> 'Copy Content' to copy raw file contents directly into your clipboard without opening the file.",
        .helpShredTitle: "Secure File Shredder",
        .helpShredDesc: "Right-click sensitive files -> 'Secure Shred File...' to permanently overwrite data blocks before unlinking.",
        .helpServerTitle: "Connect to Network Server",
        .helpWifiShareTitle: "Wi-Fi Folder Sharing",
        .helpWifiShareDesc: "Instantly share any folder over your local network via HTTP.",
        .helpAutoOrgTitle: "Auto-Organization",
        .helpAutoOrgDesc: "Set rules to automatically move incoming files into specific folders.",
        .helpServerDesc: "Press Cmd+K or choose 'Connect to Server...' in the Options menu to connect to remote SMB, FTP, or SFTP shares.",
        .navSystemTitle: "Navigation, System & Customization",
        .helpUndoTitle: "Full Undo / Redo Operations Engine",
        .helpUndoDesc: "Press Cmd+Z to undo or Cmd+Shift+Z to redo file renames, creations, moves, and deletions safely.",
        .helpPreviewTitle: "Syntax-Highlighted Preview Sidebar",
        .helpPreviewDesc: "Press Shift+Cmd+P or toggle Preview in the View menu to view syntax-highlighted code, markdown, audio, and images without opening apps.",
        .helpViewModeMemoryTitle: "Per-Directory View Mode Memory",
        .helpViewModeMemoryDesc: "Wiles remembers whether you prefer Grid, List, or Column view individually for each folder you navigate.",
        .helpPathBarTitle: "Interactive Path Bar & Breadcrumbs",
        .helpPathBarDesc: "Click any segment in the top or bottom path bar to navigate instantly. Click the edit pencil icon to manually type or paste paths.",
        .helpDragDropTitle: "Drag & Drop File Operations",
        .helpDragDropDesc: "Drag files into sidebar favorites, subfolders, or external apps. Supports box marquee selection in Grid and List views.",
        .helpI18nTitle: "Multi-Language System (i18n)",
        .helpI18nDesc: "Automatic macOS system language detection with manual preference overrides (English, Portuguese, Spanish, French, German).",
        .helpTranslucentTitle: "Translucent Background & Density Settings",
        .helpTranslucentDesc: "Adjust sidebar background glassmorphism (Translucent Level) and enable Compact Density Layout in the Options menu.",
        .navProfilesTitle: "Navigation Shortcut Profiles",
        .gnomeModeTitle: "GNOME Mode (Default)",
        .gnomeModeDesc: "• Enter: Open folder or file\n• F2: Rename item\n• Backspace: Go up to parent folder\n• Ctrl+H: Toggle hidden files",
        .macModeTitle: "macOS Finder Mode",
        .macModeDesc: "• Cmd+Down: Open folder or file\n• Enter: Rename item\n• Cmd+Up: Go up to parent folder\n• Cmd+Shift+.: Toggle hidden files",
        .shortcutsCheatsheetTitle: "Keyboard Shortcuts Cheatsheet",
        .actUndo: "Undo Operation",
        .actRedo: "Redo Operation",
        .actQuickLook: "Quick Look Preview",
        .actTogglePreview: "Toggle Preview Sidebar",
        .actToggleTerminal: "Toggle Terminal Drawer",
        .actSearch: "Search in Directory",
        .networkAndCloud: "NETWORK & CLOUD",
        .shareFolderWifi: "Share Folder over Wi-Fi",
        .autoOrganization: "Auto-Organization Rules...",
        .noAutoOrgRules: "No Auto-Organization Rules",
        .noAutoOrgRulesDesc: "Files will stay where they are.",
        .addNewRule: "Add New Rule",
        .ifFileIn: "If file in:",
        .selectFolder: "Select Folder...",
        .ruleValuePlaceholder: "Value (e.g. pdf)",
        .moveTo: "Move to:",
        .addRule: "Add Rule",
        .actDiskVisualizer: "Disk Usage Visualizer",
        .actConnectServer: "Connect to Server",
        .actNewFolderShortcut: "New Folder",
        .actItemProperties: "Item Properties / Info",
        .actCopyShortcut: "Copy Selected",
        .actCutShortcut: "Cut Selected",
        .actPasteShortcut: "Paste Files",
        .actMoveTrash: "Move to Trash",
        .actNavBackForward: "Navigate Back / Forward",
        .actParentFolder: "Parent Folder",
        .actRefreshShortcut: "Refresh Directory",
        .actToggleStatusBar: "Toggle Status Bar",
        .fullDiskAccessPromptTitle: "Full Disk Access",
        .fullDiskAccessPromptMessage: "Wiles needs Full Disk Access to browse all your folders without repeated permission prompts. Grant it once in System Settings.",
        .openSystemSettings: "Open System Settings",
        .notNow: "Not Now",
        .deleteImmediately: "Delete Immediately",
        .secureShred: "Secure Shred File...",
        .createSymlink: "Create Symlink...",
        .compressToTarGz: "Compress to .tar.gz",
        .hideTerminal: "Hide Terminal",
        .showTerminal: "Show Terminal",
        .hidePreview: "Hide Preview",
        .showNetworkAndCloud: "Show Network & Cloud",
        .back: "Back",
        .forward: "Forward",
        .goToFolder: "Go to Folder...",
        .filterImages: "Filter Images (kind:image)",
        .filterDocuments: "Filter Documents (kind:doc)",
        .filterCodeFiles: "Filter Code Files (kind:code)",
        .filterFolders: "Filter Folders (kind:folder)",
        .filterPDFs: "Filter PDFs (ext:pdf)",
        .filterLargeFiles: "Filter Large Files >10MB (size:>10m)",
        .filterModified7Days: "Modified Past 7 Days (date:7d)",
        .scanningFolderSize: "Scanning folder size...",
        .backgroundOperations: "Background Operations",
        .noActiveOperations: "No active operations",
        .sharingActive: "Sharing Active",
        .wifiShareNotice: "Anyone on your Wi-Fi network can access this folder by visiting the address above.",
        .startingServer: "Starting Server...",
        .linkType: "Link Type",
        .symlinkName: "Symlink Name",
        .noSelection: "No Selection",
        .codePreview: "Code Preview",
        .openWith: "Otwórz w programie",
        .selectOtherApp: "Inna...",
        .downloadFromiCloud: "Pobierz z iCloud",
        .smartFolders: "INTELIGENTNE FOLDERY",
        .saveSearch: "Zapisz wyszukiwanie",
        .saveAsSmartFolder: "Zapisz jako inteligentny folder...",
        .smartFolderName: "Nazwa inteligentnego folderu",
        .sharingAndPermissions: "Udostępnianie i uprawnienia",
        .read: "Odczyt",
        .write: "Zapis",
        .execute: "Wykonanie",
        .applyPermissions: "Zastosuj uprawnienia",
        .compressWithPassword: "Kompresuj z hasłem...",
        .enterPassword: "Wprowadź hasło",
        .password: "Hasło",
        .others: "Inni",
        .changeAllDefaultApp: "Zawsze otwieraj w",
        .recentServers: "Ostatnie serwery",
        .mergeIntoPDF: "Połącz w jeden plik PDF",
        .camera: "Aparat",
        .lens: "Obiektyw",
        .aperture: "Przysłona",
        .focalLength: "Ogniskowa",
        .dateTaken: "Data wykonania",
        .searchScope: "Zakres wyszukiwania",
        .searchByName: "Nazwa pliku",
        .searchByContent: "Zawartość pliku",
        .inspectArchive: "Przeglądaj archiwum...",
        .permissionDeniedNotice: "Brak dostępu: Wiles nie może odczytać zawartości tego folderu."
,
        .emptyFolder: "Ten folder jest pusty",
        .clearSearch: "Wyczyść wyszukiwanie"
,
        .grantFullDiskAccess: "Przyznaj pełny dostęp do dysku (Wszystkie foldery)...",
        .fullDiskAccessNotice: "Przyznaj pełny dostęp do dysku w Ustawieniach systemowych, aby korzystać ze wszystkich folderów bez powtarzających się monitów."
,
        .findDuplicates: "Znajdź duplikaty plików...",
        .duplicateCleanerTitle: "Czyszczenie duplikatów",
        .reclaimableSpace: "Miejsce do odzyskania",
        .trashSelectedDuplicates: "Przenieś zaznaczone duplikaty do kosza",
        .noDuplicatesFound: "Nie znaleziono duplikatów plików",
        .batchRenameTitle: "Wsadowa zmiana nazw plików",
        .namingPattern: "Wzorzec nazwy",
        .regexReplace: "Wzorzec Regex"
    ]
}
