import Foundation

extension L10n {
    static let es: [Key: String] = [
        .newFolder: "Nueva Carpeta...",
        .paste: "Pegar",
        .selectAll: "Seleccionar Todo",
        .sortBy: "Ordenar por",
        .viewMode: "Modo de Vista",
        .gridView: "Vista de Cuadrícula",
        .listView: "Vista de Lista",
        .showHiddenFiles: "Mostrar Archivos Ocultos",
        .showHiddenFilesGnome: "Mostrar Arquivos Ocultos (Ctrl+H)",
        .showHiddenFilesMac: "Mostrar Arquivos Ocultos (Cmd+Shift+.)",
        .hideStatusBar: "Ocultar Barra de Estado",
        .showStatusBar: "Mostrar Barra de Estado",
        .showFavorites: "Mostrar Favoritos",
        .showMacSection: "Mostrar Sección MAC",
        .showRecents: "Mostrar Recientes",
        .sidebarMode: "Modo de Barra Lateral",
        .places: "Lugares y Dispositivos",
        .shortcutMode: "Modo de Atajos",
        .refresh: "Actualizar",
        .copyPath: "Copiar Ruta",
        .folderProperties: "Propiedades de la Carpeta",
        .open: "Abrir",
        .quickLook: "Vista Rápida",
        .removeFromFavorites: "Eliminar de Favoritos",
        .addToFavorites: "Adicionar a Favoritos",
        .cut: "Cortar",
        .copy: "Copiar",
        .copyContent: "Copiar Contenido",
        .moveToTrash: "Mover a la Papelera",
        .compressToZip: "Comprimir a ZIP",
        .extractHere: "Extraer Archivo Aquí",
        .rename: "Renombrar...",
        .properties: "Propiedades",
        .noResultsFound: "Sin Resultados",
        .folderIsEmpty: "La Carpeta está Vacía",
        .name: "Nombre",
        .size: "Tamaño",
        .dateModified: "Fecha de Modificación",
        .kind: "Clase",
        .folder: "Carpeta",
        .favorites: "FAVORITOS",
        .mac: "MAC",
        .recents: "RECIENTES",
        .devices: "DISPOSITIVOS",
        .directoryTree: "ÁRBOLES DE DIRECTORIOS",
        .searchPlaceholder: "Buscar en",
        .home: "Inicio",
        .desktop: "Escritorio",
        .documents: "Documentos",
        .downloads: "Descargas",
        .music: "Música",
        .pictures: "Imágenes",
        .movies: "Películas",
        .trash: "Papelera",
        .applications: "Aplicaciones",
        .airDrop: "AirDrop",
        .iCloudDrive: "iCloud Drive",
        .freeSpace: "libre",
        .language: "Idioma",
        .cancel: "Cancelar",
        .create: "Crear",
        .createNewFolder: "Crear Nueva Carpeta",
        .folderNamePlaceholder: "Nombre de la Carpeta",
        .defaultFolderName: "Nueva Carpeta",
        .enterPathPlaceholder: "Ingrese ruta...",
        .root: "Raíz",
        .ascending: "Ascendente",
        .location: "Ubicación",
        .modified: "Modificado",
        .hidden: "Oculto",
        .yes: "Sí",
        .no: "No",
        .close: "Cerrar",
        .parentFolder: "Carpeta Superior",
        .done: "Hecho",
        .helpShortcuts: "Ayuda y Atajos",
        .batchRename: "Renombrar en Lote",
        .find: "Buscar",
        .replaceWith: "Reemplazar por",
        .prefix: "Prefijo",
        .suffix: "Sufijo",
        .sequenceNumbering: "Numeración Secuencial",
        .startNumber: "Número Inicial",
        .preview: "Previsualización",
        .originalName: "Nombre Original",
        .newName: "Nuevo Nombre",
        .apply: "Aplicar",
        .quickConvertImage: "Conversión Rápida de Imagen...",
        .targetFormat: "Formato de Destino",
        .resizePreset: "Tamaño de Imagen",
        .cropPreset: "Recorte de Aspecto",
        .quality: "Calidad",
        .convert: "Convertir",
        .diskUsageVisualizer: "Visualizador de Uso de Disco",
        .topLargestItems: "Principales Elementos por Tamaño",
        .aboutWiles: "Acerca de Wiles",
        .aboutDescription: "Un administrador de archivos nativo de macOS, súper rápido y diseñado para unir lo mejor de GNOME Files y Finder.",
        .createdBy: "Creado por Marco PS",
        .version: "Versión",
        .translucentLevel: "Transparencia",
        .sidebarTranslucentLevel: "Transparencia Lateral",
        .contentTranslucentLevel: "Transparencia del Contenido",
        .showPreviewSidebar: "Mostrar Vista Previa",
        .moreInfo: "Más Información...",
        .general: "General",
        .permissions: "Compartir y Permisos",
        .owner: "Propietario",
        .group: "Grupo",
        .created: "Creado",
        .lastOpened: "Último Acceso",
        .dimensions: "Dimensiones",
        .duration: "Duración",
        .fetchError: "No se pudieron cargar las propiedades.",
        .newFileTitle: "Nuevo Archivo",
        .selectTemplate: "Seleccionar Plantilla",
        .fileNameLabel: "Nombre del Archivo",
        .extractArchive: "Extraer Archivo",
        .connectToServer: "Conectarse al Servidor",
        .connect: "Conectar",
        .showTags: "Mostrar Etiquetas",
        .tags: "Etiquetas",
        .red: "Rojo",
        .orange: "Naranja",
        .yellow: "Amarillo",
        .green: "Verde",
        .blue: "Azul",
        .purple: "Morado",
        .gray: "Gris",
        .clearAllTags: "Borrar todas las etiquetas",
        .services: "Servicios",
        .compactDensity: "Diseño de Densidad Compacta",
        .helpGuideTitle: "Guía de Ayuda y Funciones",
        .tabOverview: "Visión General",
        .tabFeatures: "Funciones y Herramientas",
        .tabSystem: "Navegación y Sistema",
        .tabShortcuts: "Atajos",
        .overviewDesc: "Wiles es un administrador de archivos nativo de alto rendimiento para macOS construído con AppKit y SwiftUI.",
        .domainToolsTitle: "Herramientas del Dominio y Destacados",
        .helpTagsTitle: "Etiquetas Nativas de macOS y Filtrado",
        .helpTagsDesc: "Active 'Mostrar Etiquetas' en el menú Vista u Opciones.",
        .helpTerminalTitle: "Abrir en Terminal",
        .helpTerminalDesc: "Haga clic derecho en cualquier carpeta -> 'Abrir en Terminal'.",
        .helpZipTitle: "Compresión y Extracción de Archivos ZIP",
        .helpZipDesc: "Haga clic derecho -> 'Comprimir a ZIP' o 'Extraer Aquí'.",
        .helpDiskTitle: "Visualizador de Espacio en Disco",
        .helpDiskDesc: "Presione Shift+Cmd+D para inspeccionar archivos grandes.",
        .helpImageTitle: "Convertidor Rápido de Imágenes",
        .helpImageDesc: "Haga clic derecho en una imagen -> 'Conversión Rápida de Imagen...'.",
        .helpBatchTitle: "Herramienta de Renombrado en Lote",
        .helpBatchDesc: "Seleccione varios archivos y presione F2 para renombrar en lote.",
        .helpSymlinkTitle: "Creación de Enlaces Simbólicos",
        .helpSymlinkDesc: "Haga clic derecho -> 'Crear Enlace Simbólico...'.",
        .helpTemplateTitle: "Plantillas de Nuevos Archivos",
        .helpTemplateDesc: "Haga clic derecho en el fondo -> 'Nuevo Archivo...'.",
        .helpCopyContentTitle: "Copiar Contenido del Archivo al Portapapeles",
        .helpCopyContentDesc: "Haga clic derecho -> 'Copiar Contenido'.",
        .helpShredTitle: "Trituradora Segura de Archivos",
        .helpShredDesc: "Haga clic derecho -> 'Triturar Archivo...'.",
        .helpServerTitle: "Conectarse al Servidor de Red",
        .helpWifiShareTitle: "Compartir por Wi-Fi",
        .helpWifiShareDesc: "Comparte carpetas al instante en tu red local vía HTTP.",
        .helpAutoOrgTitle: "Organización Automática",
        .helpAutoOrgDesc: "Crea reglas para mover archivos automáticamente a carpetas específicas.",
        .helpServerDesc: "Presione Cmd+K para conectarse a servidores de red.",
        .navSystemTitle: "Navegación, Sistema y Personalización",
        .helpUndoTitle: "Motor Completo de Deshacer / Rehacer",
        .helpUndoDesc: "Presione Cmd+Z para deshacer o Cmd+Shift+Z para rehacer.",
        .helpPreviewTitle: "Barra Lateral de Vista Previa con Resaltado de Sintaxis",
        .helpPreviewDesc: "Presione Shift+Cmd+P para ver vista previa.",
        .helpViewModeMemoryTitle: "Memoria de Modo de Vista por Directorio",
        .helpViewModeMemoryDesc: "Wiles recuerda la vista preferida para cada carpeta.",
        .helpPathBarTitle: "Barra de Ruta Interactiva",
        .helpPathBarDesc: "Haga clic en cualquier segmento para navegar.",
        .helpDragDropTitle: "Operaciones de Arrastrar y Soltar",
        .helpDragDropDesc: "Arrastre archivos a favoritos o carpetas.",
        .helpI18nTitle: "Sistema Multilingüe (i18n)",
        .helpI18nDesc: "Detección automática del idioma del sistema con opción manual.",
        .helpTranslucentTitle: "Fondo Traslúcido y Configuración de Densidad",
        .helpTranslucentDesc: "Ajuste la transparencia y la densidad compacta.",
        .navProfilesTitle: "Perfiles de Atajos de Navegación",
        .gnomeModeTitle: "Modo GNOME (Predeterminado)",
        .gnomeModeDesc: "• Enter: Abrir carpeta\n• F2: Renombrar\n• Backspace: Carpeta superior\n• Ctrl+H: Archivos ocultos",
        .macModeTitle: "Modo macOS Finder",
        .macModeDesc: "• Cmd+Abajo: Abrir carpeta\n• Enter: Renombrar\n• Cmd+Arriba: Carpeta superior\n• Cmd+Shift+.: Archivos ocultos",
        .shortcutsCheatsheetTitle: "Lista de Atajos de Teclado",
        .actUndo: "Deshacer Operación",
        .actRedo: "Rehacer Operación",
        .actQuickLook: "Vista Previa Quick Look",
        .actTogglePreview: "Alternar Barra Lateral de Vista Previa",
        .actToggleTerminal: "Alternar Terminal Integrado",
        .actSearch: "Buscar en el Directorio",
        .networkAndCloud: "RED Y NUBE",
        .shareFolderWifi: "Compartir Carpeta por Wi-Fi",
        .autoOrganization: "Reglas de Organización Automática...",
        .noAutoOrgRules: "Sin reglas",
        .noAutoOrgRulesDesc: "Los archivos no se moverán.",
        .addNewRule: "Añadir nueva regla",
        .ifFileIn: "Si el archivo en:",
        .selectFolder: "Seleccionar carpeta...",
        .ruleValuePlaceholder: "Valor (ej: pdf)",
        .moveTo: "Mover a:",
        .addRule: "Añadir regla",
        .actDiskVisualizer: "Visualizador de Uso de Disco",
        .actConnectServer: "Conectarse al Servidor",
        .actNewFolderShortcut: "Nueva Carpeta",
        .actItemProperties: "Propiedades / Información del Elemento",
        .actCopyShortcut: "Copiar Seleccionado",
        .actCutShortcut: "Cortar Seleccionado",
        .actPasteShortcut: "Pegar Archivos",
        .actMoveTrash: "Mover a la Papelera",
        .actNavBackForward: "Navegar Atrás / Adelante",
        .actParentFolder: "Carpeta Superior",
        .actRefreshShortcut: "Actualizar Directorio",
        .actToggleStatusBar: "Alternar Barra de Estado",
        .fullDiskAccessPromptTitle: "Acceso Total al Disco",
        .fullDiskAccessPromptMessage: "Wiles necesita Acceso Total al Disco para explorar todas tus carpetas sin solicitudes de permiso repetidas. Concédelo una vez en Ajustes del Sistema.",
        .openSystemSettings: "Abrir Ajustes del Sistema",
        .notNow: "Ahora No"
,
        .deleteImmediately: "Eliminar Inmediatamente",
        .secureShred: "Destruir Archivo de Forma Segura...",
        .createSymlink: "Crear Enlace Simbólico...",
        .compressToTarGz: "Comprimir a .tar.gz",
        .hideTerminal: "Ocultar Terminal",
        .showTerminal: "Mostrar Terminal",
        .hidePreview: "Ocultar Vista Previa",
        .showNetworkAndCloud: "Mostrar Red y Nube",
        .back: "Atrás",
        .forward: "Adelante",
        .goToFolder: "Ir a la Carpeta...",
        .filterImages: "Filtrar Imágenes (kind:image)",
        .filterDocuments: "Filtrar Documentos (kind:doc)",
        .filterCodeFiles: "Filtrar Archivos de Código (kind:code)",
        .filterFolders: "Filtrar Carpetas (kind:folder)",
        .filterPDFs: "Filtrar PDFs (ext:pdf)",
        .filterLargeFiles: "Filtrar Archivos Grandes >10MB (size:>10m)",
        .filterModified7Days: "Modificados en Últimos 7 Días (date:7d)",
        .scanningFolderSize: "Analizando tamaño de la carpeta...",
        .backgroundOperations: "Operaciones en Segundo Plano",
        .noActiveOperations: "Sin operaciones activas",
        .sharingActive: "Compartición Activa",
        .wifiShareNotice: "Cualquier persona en tu red Wi-Fi puede acceder a esta carpeta visitando la dirección de arriba.",
        .startingServer: "Iniciando Servidor...",
        .linkType: "Tipo de Enlace",
        .symlinkName: "Nombre del Enlace Simbólico",
        .noSelection: "Sin Selección",
        .codePreview: "Vista Previa de Código"
,
        .openWith: "Abrir con",
        .permissionDeniedNotice: "Permiso Denegado: Wiles no puede leer el contenido de esta carpeta."
,
        .emptyFolder: "Esta carpeta está vacía",
        .clearSearch: "Limpiar búsqueda"
,
        .grantFullDiskAccess: "Conceder acceso total al disco (Todas las carpetas)...",
        .fullDiskAccessNotice: "Conceda acceso total al disco en Configuración del Sistema para acceder a todas las carpetas sin avisos repetidos."
,
        .findDuplicates: "Buscar archivos duplicados...",
        .duplicateCleanerTitle: "Limpiador de archivos duplicados",
        .reclaimableSpace: "Espacio recuperable",
        .trashSelectedDuplicates: "Mover duplicados seleccionados a la papelera",
        .noDuplicatesFound: "No se encontraron archivos duplicados",
        .batchRenameTitle: "Renombrar archivos en lote",
        .namingPattern: "Patrón de nombre",
        .regexReplace: "Patrón Regex",
        .emptyTrash: "Vaciar papelera",
        .emptyTrashConfirm: "¿Está seguro de que desea eliminar permanentemente todos los elementos de la papelera?"
    ]
}
