import Foundation

extension L10n {
    static let fr: [Key: String] = [
        .newFolder: "Nouveau dossier...",
        .paste: "Coller",
        .selectAll: "Tout sélectionner",
        .sortBy: "Trier par",
        .viewMode: "Mode d'affichage",
        .gridView: "Affichage en grille",
        .listView: "Affichage en liste",
        .showHiddenFiles: "Afficher les fichiers masqués",
        .showHiddenFilesGnome: "Afficher les fichiers masqués (Ctrl+H)",
        .showHiddenFilesMac: "Afficher les fichiers masqués (Cmd+Shift+.)",
        .hideStatusBar: "Masquer la barre d'état",
        .showStatusBar: "Afficher la barre d'état",
        .showFavorites: "Afficher les favoris",
        .showMacSection: "Afficher la section MAC",
        .showRecents: "Afficher les récents",
        .showPlaces: "Afficher les emplacements",
        .showSidebarSectionTitles: "Afficher les titres de la barre latérale",
        .sidebarMode: "Mode barre latérale",
        .places: "Emplacements & Dispositifs",
        .shortcutMode: "Mode raccourcis",
        .refresh: "Actualiser",
        .copyPath: "Copier le chemin",
        .copyPathAbsolute: "Chemin absolu",
        .copyPathRelative: "Chemin relatif",
        .copyPathURL: "URL du fichier (file://)",
        .copyPathTerminal: "Chemin échappé pour Terminal",
        .folderProperties: "Propriétés du dossier",
        .open: "Ouvrir",
        .quickLook: "Aperçu rapide",
        .removeFromFavorites: "Retirer des favoris",
        .addToFavorites: "Ajouter aux favoris",
        .cut: "Couper",
        .copy: "Copier",
        .copyContent: "Copier le contenu",
        .moveToTrash: "Placer dans la Corbeille",
        .compressToZip: "Compresser en ZIP",
        .extractHere: "Extraire l'archive ici",
        .rename: "Renommer...",
        .properties: "Propriétés",
        .noResultsFound: "Aucun résultat trouvé",
        .folderIsEmpty: "Le dossier est vide",
        .name: "Nom",
        .size: "Taille",
        .dateModified: "Date de modification",
        .kind: "Type",
        .folder: "Dossier",
        .favorites: "FAVORIS",
        .mac: "MAC",
        .recents: "RÉCENTS",
        .devices: "DISPOSITIVOS",
        .directoryTree: "ARBORESCENCE",
        .searchPlaceholder: "Rechercher dans",
        .home: "Départ",
        .desktop: "Bureau",
        .documents: "Documents",
        .downloads: "Téléchargements",
        .music: "Musique",
        .pictures: "Images",
        .movies: "Films",
        .trash: "Corbeille",
        .applications: "Applications",
        .airDrop: "AirDrop",
        .iCloudDrive: "iCloud Drive",
        .freeSpace: "libre",
        .language: "Langue",
        .cancel: "Annuler",
        .create: "Créer",
        .createNewFolder: "Créer un nouveau dossier",
        .folderNamePlaceholder: "Nom du dossier",
        .defaultFolderName: "Nouveau dossier",
        .enterPathPlaceholder: "Entrer le chemin...",
        .root: "Racine",
        .ascending: "Croissant",
        .location: "Emplacement",
        .modified: "Modifié",
        .hidden: "Masqué",
        .yes: "Oui",
        .no: "Non",
        .close: "Fermer",
        .parentFolder: "Dossier parent",
        .done: "Terminé",
        .helpShortcuts: "Aide et raccourcis",
        .batchRename: "Renommer en lot",
        .find: "Rechercher",
        .replaceWith: "Remplacer par",
        .prefix: "Préfixe",
        .suffix: "Suffixe",
        .sequenceNumbering: "Numérotation séquentielle",
        .startNumber: "Numéro de départ",
        .preview: "Aperçu",
        .originalName: "Nom d'origine",
        .newName: "Nouveau nom",
        .apply: "Appliquer",
        .quickConvertImage: "Conversion rapide d'image...",
        .targetFormat: "Format de destination",
        .resizePreset: "Taille de l'image",
        .cropPreset: "Rognage du format",
        .quality: "Qualité",
        .convert: "Convertir",
        .diskUsageVisualizer: "Visualiseur d'espace disque",
        .topLargestItems: "Éléments les plus volumineux",
        .aboutWiles: "À propos de Wiles",
        .aboutDescription: "Un gestionnaire de fichiers natif de macOS, très rapide et conçu pour réunir le meilleur de GNOME Files et Finder.",
        .createdBy: "Créé par Marco PS",
        .version: "Version",
        .translucentLevel: "Translucidité",
        .sidebarTranslucentLevel: "Translucidité de la Barre Latérale",
        .contentTranslucentLevel: "Translucidité du Contenu",
        .showPreviewSidebar: "Afficher l'aperçu",
        .moreInfo: "Plus d'infos...",
        .general: "Général",
        .permissions: "Partage et permissions",
        .owner: "Propriétaire",
        .group: "Groupe",
        .created: "Créé",
        .lastOpened: "Dernière ouverture",
        .dimensions: "Dimensions",
        .duration: "Durée",
        .fetchError: "Impossible de charger les propriétés.",
        .newFileTitle: "Nouveau Fichier",
        .selectTemplate: "Sélectionner un Modèle",
        .fileNameLabel: "Nom du Fichier",
        .extractArchive: "Extraire L'Archive",
        .connectToServer: "Se Connecter au Serveur",
        .connect: "Connecter",
        .showTags: "Afficher les étiquettes",
        .tags: "Étiquettes",
        .red: "Rouge",
        .orange: "Orange",
        .yellow: "Jaune",
        .green: "Vert",
        .blue: "Bleu",
        .purple: "Violet",
        .gray: "Gris",
        .clearAllTags: "Effacer toutes les étiquettes",
        .services: "Services",
        .compactDensity: "Disposition à densité compacte",
        .helpGuideTitle: "Guide d'Aide et Fonctionnalités",
        .tabOverview: "Aperçu",
        .tabFeatures: "Fonctionnalités et Outils",
        .tabSystem: "Navigation et Système",
        .tabShortcuts: "Raccourcis",
        .overviewDesc: "Wiles est un gestionnaire de fichiers macOS natif et performant.",
        .domainToolsTitle: "Outils du Domaine et Points Forts",
        .helpTagsTitle: "Étiquettes N 커 de macOS et Filtrage",
        .helpTagsDesc: "Activez 'Afficher les étiquettes' dans le menu Présentation.",
        .helpTerminalTitle: "Ouvrir dans le Terminal",
        .helpTerminalDesc: "Faites un clic droit sur n'importe quel dossier -> 'Ouvrir dans le Terminal'.",
        .helpZipTitle: "Compression et Extraction d'Archives ZIP",
        .helpZipDesc: "Clic droit -> 'Compresser en ZIP' ou 'Extraire ici'.",
        .helpDiskTitle: "Visualiseur d'Espace Disque",
        .helpDiskDesc: "Appuyez sur Shift+Cmd+D pour inspecter les fichiers volumineux.",
        .helpImageTitle: "Convertisseur Rapide d'Images",
        .helpImageDesc: "Clic droit sur une image -> 'Convertir rapidement l'image...'.",
        .helpBatchTitle: "Outil de Renommage en Lot",
        .helpBatchDesc: "Sélectionnez plusieurs fichiers et appuyez sur F2.",
        .helpSymlinkTitle: "Création de Liens Symboliques",
        .helpSymlinkDesc: "Clic droit -> 'Créer un lien symbolique...'.",
        .helpTemplateTitle: "Modèles de Nouveaux Fichiers",
        .helpTemplateDesc: "Clic droit sur l'arrière-plan -> 'Nouveau fichier...'.",
        .helpCopyContentTitle: "Copier le Contenu du Fichier dans le Presse-papiers",
        .helpCopyContentDesc: "Clic droit -> 'Copier le contenu'.",
        .helpShredTitle: "Broyeur Sécurisé de Fichiers",
        .helpShredDesc: "Clic droit -> 'Broyer le fichier...'.",
        .helpServerTitle: "Se Connecter au Serveur Réseau",
        .helpWifiShareTitle: "Partage Wi-Fi",
        .helpWifiShareDesc: "Partagez instantanément n'importe quel dossier sur votre réseau local via HTTP.",
        .helpAutoOrgTitle: "Organisation Automatique",
        .helpAutoOrgDesc: "Définissez des règles pour déplacer automatiquement les fichiers entrants.",
        .helpServerDesc: "Appuyez sur Cmd+K pour vous connecter à un serveur réseau.",
        .navSystemTitle: "Navigation, Système et Personnalisation",
        .helpUndoTitle: "Moteur Complet Annuler / Rétablir",
        .helpUndoDesc: "Appuyez sur Cmd+Z pour annuler ou Cmd+Shift+Z pour rétablir.",
        .helpPreviewTitle: "Barre Latérale d'Aperçu avec Coloration Syntaxique",
        .helpPreviewDesc: "Appuyez sur Shift+Cmd+P pour afficher l'aperçu.",
        .helpViewModeMemoryTitle: "Mémoire du Mode d'Affichage par Dossier",
        .helpViewModeMemoryDesc: "Wiles se souvient du mode d'affichage préféré pour chaque dossier.",
        .helpPathBarTitle: "Barre de Chemin Interactive",
        .helpPathBarDesc: "Cliquez sur n'importe quel segment pour naviguer.",
        .helpDragDropTitle: "Glisser-déposer de Fichiers",
        .helpDragDropDesc: "Glissez des fichiers dans les favoris ou dossiers.",
        .helpI18nTitle: "Système Multilingue (i18n)",
        .helpI18nDesc: "Détection automatique de la langue avec choix manuel.",
        .helpTranslucentTitle: "Arrière-plan Translucide et Densité",
        .helpTranslucentDesc: "Ajustez la transparence et la densité compacte.",
        .navProfilesTitle: "Profils de Raccourcis de Navigation",
        .gnomeModeTitle: "Mode GNOME (Par défaut)",
        .gnomeModeDesc: "• Entrée: Ouvrir le dossier\n• F2: Renommer\n• Retour arrière: Dossier parent\n• Ctrl+H: Fichiers masqués",
        .macModeTitle: "Mode macOS Finder",
        .macModeDesc: "• Cmd+Bas: Ouvrir le dossier\n• Entrée: Renommer\n• Cmd+Haut: Dossier parent\n• Cmd+Shift+.: Fichiers masqués",
        .shortcutsCheatsheetTitle: "Aide-mémoire des Raccourcis Clavier",
        .actUndo: "Annuler l'opération",
        .actRedo: "Rétablir l'opération",
        .actQuickLook: "Aperçu Coup d'œil",
        .actTogglePreview: "Basculer la barre d'aperçu",
        .actToggleTerminal: "Basculer le terminal intégré",
        .actSearch: "Rechercher dans le dossier",
        .networkAndCloud: "RÉSEAU ET CLOUD",
        .shareFolderWifi: "Partager le dossier via Wi-Fi",
        .autoOrganization: "Règles d'organisation automatique...",
        .noAutoOrgRules: "Aucune règle",
        .noAutoOrgRulesDesc: "Les fichiers ne seront pas déplacés.",
        .addNewRule: "Ajouter une nouvelle règle",
        .ifFileIn: "Si fichier dans:",
        .selectFolder: "Sélectionner un dossier...",
        .ruleValuePlaceholder: "Valeur (ex: pdf)",
        .moveTo: "Déplacer vers:",
        .addRule: "Ajouter la règle",
        .actDiskVisualizer: "Visualiseur d'espace disque",
        .actConnectServer: "Se connecter au serveur",
        .actNewFolderShortcut: "Nouveau dossier",
        .actItemProperties: "Propriétés du fichier",
        .actCopyShortcut: "Copier la sélection",
        .actCutShortcut: "Couper la sélection",
        .actPasteShortcut: "Coller les fichiers",
        .actMoveTrash: "Placer dans la corbeille",
        .actNavBackForward: "Naviguer Précédent / Suivant",
        .actParentFolder: "Dossier parent",
        .actRefreshShortcut: "Actualiser le dossier",
        .actToggleStatusBar: "Basculer la barre d'état",
        .fullDiskAccessPromptTitle: "Accès complet au disque",
        .fullDiskAccessPromptMessage: "Wiles a besoin d'un accès complet au disque pour parcourir tous vos dossiers sans demandes d'autorisation répétées. Accordez-le une fois dans Réglages Système.",
        .openSystemSettings: "Ouvrir Réglages Système",
        .notNow: "Plus tard"
,
        .deleteImmediately: "Supprimer immédiatement",
        .secureShred: "Broyer le fichier en toute sécurité...",
        .createSymlink: "Créer un lien symbolique...",
        .compressToTarGz: "Compresser en .tar.gz",
        .hideTerminal: "Masquer le terminal",
        .showTerminal: "Afficher le terminal",
        .hidePreview: "Masquer l'aperçu",
        .showNetworkAndCloud: "Afficher réseau et cloud",
        .back: "Retour",
        .forward: "Avancer",
        .goToFolder: "Aller au dossier...",
        .filterImages: "Filtrer images (kind:image)",
        .filterDocuments: "Filtrer documents (kind:doc)",
        .filterCodeFiles: "Filtrer fichiers de code (kind:code)",
        .filterFolders: "Filtrer dossiers (kind:folder)",
        .filterPDFs: "Filtrer PDF (ext:pdf)",
        .filterLargeFiles: "Filtrer grands fichiers >10MB (size:>10m)",
        .filterModified7Days: "Modifié les 7 derniers jours (date:7d)",
        .scanningFolderSize: "Analyse de la taille du dossier...",
        .backgroundOperations: "Opérations en arrière-plan",
        .noActiveOperations: "Aucune opération active",
        .sharingActive: "Partage actif",
        .wifiShareNotice: "Toute personne sur votre réseau Wi-Fi peut accéder à ce dossier en visitant l'adresse ci-dessus.",
        .startingServer: "Démarrage du serveur...",
        .linkType: "Type de lien",
        .symlinkName: "Nom du lien symbolique",
        .noSelection: "Aucune sélection",
        .codePreview: "Aperçu du code"
,
        .openWith: "Ouvrir avec",
        .selectOtherApp: "Autre...",
        .downloadFromiCloud: "Télécharger depuis iCloud",
        .smartFolders: "DOSSIERS INTELLIGENTS",
        .saveSearch: "Enregistrer la recherche",
        .saveAsSmartFolder: "Enregistrer comme dossier intelligent...",
        .smartFolderName: "Nom du dossier intelligent",
        .sharingAndPermissions: "Partage et autorisations",
        .read: "Lecture",
        .write: "Écriture",
        .execute: "Exécution",
        .applyPermissions: "Appliquer les autorisations",
        .compressWithPassword: "Compresser avec mot de passe...",
        .enterPassword: "Entrer le mot de passe",
        .password: "Mot de passe",
        .others: "Autres",
        .permissionDeniedNotice: "Permission refusée : Wiles ne peut pas lire le contenu de ce dossier."
,
        .emptyFolder: "Ce dossier est vide",
        .clearSearch: "Effacer la recherche"
,
        .grantFullDiskAccess: "Accorder un accès complet au disque (Tous les dossiers)...",
        .fullDiskAccessNotice: "Accordez un accès complet au disque dans Réglages Système pour accéder à tous les dossiers sans demandes répétées."
,
        .findDuplicates: "Rechercher les fichiers en double...",
        .duplicateCleanerTitle: "Nettoyeur de doublons",
        .reclaimableSpace: "Espace récupérable",
        .trashSelectedDuplicates: "Déplacer les doublons sélectionnés vers la corbeille",
        .noDuplicatesFound: "Aucun fichier en double trouvé",
        .batchRenameTitle: "Renommer les fichiers en lot",
        .namingPattern: "Modèle de nom",
        .regexReplace: "Modèle Regex",
        .emptyTrash: "Vider la corbeille",
        .emptyTrashConfirm: "Voulez-vous vraiment supprimer définitivement tous les éléments de la corbeille ?"
    ]
}
