import Foundation

extension L10n {
    static let pt: [Key: String] = [
        .newFolder: "Nova Pasta...",
        .paste: "Colar",
        .selectAll: "Selecionar Tudo",
        .sortBy: "Ordenar por",
        .viewMode: "Modo de Visualização",
        .gridView: "Visualização em Grade",
        .listView: "Visualização em Lista",
        .columnView: "Visualização em Colunas",
        .showHiddenFiles: "Mostrar Arquivos Ocultos",
        .showHiddenFilesGnome: "Mostrar Arquivos Ocultos (Ctrl+H)",
        .showHiddenFilesMac: "Mostrar Arquivos Ocultos (Cmd+Shift+.)",
        .hideStatusBar: "Ocultar Barra de Status",
        .showStatusBar: "Mostrar Barra de Status",
        .showFavorites: "Mostrar Favoritos",
        .showMacSection: "Mostrar Seção MAC",
        .showRecents: "Mostrar Recentes",
        .showPlaces: "Mostrar Locais",
        .sidebarMode: "Modo da Barra Lateral",
        .places: "LOCAIS",
        .placesMenuOption: "Locais",
        .treeMenuOption: "Árvore de Diretórios",
        .shortcutMode: "Modo de Atalhos",
        .refresh: "Atualizar",
        .copyPath: "Copiar Caminho",
        .folderProperties: "Propriedades da Pasta",
        .open: "Abrir",
        .quickLook: "Visualização Rápida",
        .removeFromFavorites: "Remover dos Favoritos",
        .addToFavorites: "Adicionar aos Favoritos",
        .cut: "Recortar",
        .copy: "Copiar",
        .copyContent: "Copiar Conteúdo",
        .moveToTrash: "Mover para a Lixeira",
        .compressToZip: "Compactar para ZIP",
        .extractHere: "Extrair Arquivo Aqui",
        .rename: "Renomear...",
        .properties: "Propriedades",
        .noResultsFound: "Nenhum Resultado Encontrado",
        .folderIsEmpty: "A Pasta está Vazia",
        .name: "Nome",
        .size: "Tamanho",
        .dateModified: "Data de Modificação",
        .kind: "Tipo",
        .folder: "Pasta",
        .favorites: "FAVORITOS",
        .mac: "MAC",
        .recents: "Recentes",
        .devices: "DISPOSITIVOS",
        .directoryTree: "ÁRVORE DE DIRETÓRIOS",
        .searchPlaceholder: "Buscar em",
        .home: "Início",
        .desktop: "Mesa (Desktop)",
        .documents: "Documentos",
        .downloads: "Downloads",
        .music: "Música",
        .pictures: "Imagens",
        .movies: "Filmes",
        .trash: "Lixeira",
        .applications: "Aplicativos",
        .airDrop: "AirDrop",
        .iCloudDrive: "iCloud Drive",
        .freeSpace: "livre",
        .language: "Idioma",
        .cancel: "Cancelar",
        .create: "Criar",
        .createNewFolder: "Criar Nova Pasta",
        .folderNamePlaceholder: "Nome da Pasta",
        .defaultFolderName: "Nova Pasta",
        .enterPathPlaceholder: "Digite o caminho...",
        .root: "Raíz",
        .ascending: "Crescente",
        .location: "Localização",
        .modified: "Modificado",
        .hidden: "Oculto",
        .yes: "Sim",
        .no: "Não",
        .close: "Fechar",
        .parentFolder: "Pasta Superior",
        .done: "Concluído",
        .helpShortcuts: "Ajuda e Atalhos",
        .batchRename: "Renomear em Lote",
        .find: "Localizar",
        .replaceWith: "Substituir Por",
        .prefix: "Prefixo",
        .suffix: "Sufixo",
        .sequenceNumbering: "Numeração Sequencial",
        .startNumber: "Número Inicial",
        .preview: "Pré-visualização",
        .originalName: "Nome Original",
        .newName: "Novo Nome",
        .apply: "Aplicar",
        .quickConvertImage: "Conversão Rápida de Imagem...",
        .targetFormat: "Formato de Destino",
        .resizePreset: "Tamanho da Imagem",
        .cropPreset: "Recorte de Proporção",
        .quality: "Qualidade",
        .convert: "Converter",
        .diskUsageVisualizer: "Visualizador de Uso de Disco",
        .topLargestItems: "Principais Itens por Tamanho",
        .aboutWiles: "Sobre o Wiles",
        .aboutDescription: "Um gerenciador de arquivos nativo do macOS, super rápido e projetado para unir o melhor do GNOME Files e Finder.",
        .createdBy: "Criado por Marco PS",
        .version: "Versão",
        .translucentLevel: "Transparência",
        .sidebarTranslucentLevel: "Transparência da Lateral",
        .contentTranslucentLevel: "Transparência do Conteúdo",
        .showPreviewSidebar: "Mostrar Pré-visualização",
        .moreInfo: "Mais Informações...",
        .general: "Geral",
        .permissions: "Compartilhamento e Permissões",
        .owner: "Proprietário",
        .group: "Grupo",
        .created: "Criado",
        .lastOpened: "Último Acesso",
        .dimensions: "Dimensões",
        .duration: "Duração",
        .fetchError: "Não foi possível carregar propriedades.",
        .newFileTitle: "Novo Arquivo",
        .selectTemplate: "Selecionar Template",
        .fileNameLabel: "Nome do Arquivo",
        .extractArchive: "Extrair Arquivo",
        .connectToServer: "Conectar ao Servidor",
        .connect: "Conectar",
        .showTags: "Mostrar Etiquetas",
        .tags: "Etiquetas",
        .red: "Vermelho",
        .orange: "Laranja",
        .yellow: "Amarelo",
        .green: "Verde",
        .blue: "Azul",
        .purple: "Roxo",
        .gray: "Cinza",
        .clearAllTags: "Limpar Todas as Etiquetas",
        .services: "Serviços",
        .compactDensity: "Layout de Densidade Compacta",
        .helpGuideTitle: "Guia de Ajuda e Recursos",
        .tabOverview: "Visão Geral",
        .tabFeatures: "Recursos e Ferramentas",
        .tabSystem: "Navegação e Sistema",
        .tabShortcuts: "Atalhos",
        .overviewDesc: "O Wiles é um gerenciador de arquivos nativo de alto desempenho para macOS construído com AppKit e SwiftUI. Ele une a eficiência do GNOME Files (Nautilus) aos recursos do macOS Finder.",
        .domainToolsTitle: "Ferramentas do Domínio e Destaques",
        .helpTagsTitle: "Etiquetas Nativas do macOS e Filtragem",
        .helpTagsDesc: "Ative 'Mostrar Etiquetas' no menu Visualizar ou Opções. Clique com o botão direito no arquivo > Etiquetas. Clique na barra lateral ou busque 'tag:cor' para filtrar.",
        .helpTerminalTitle: "Abrir no Terminal",
        .helpTerminalDesc: "Clique com o botão direito em qualquer pasta ou área vazia -> 'Abrir no Terminal' para abrir o Terminal nativo na pasta atual.",
        .helpZipTitle: "Compactação e Extração de Arquivos ZIP",
        .helpZipDesc: "Clique com o botão direito nos arquivos -> 'Compactar para ZIP' ou em um .zip -> 'Extrair Aqui'.",
        .helpDiskTitle: "Visualizador de Espaço em Disco",
        .helpDiskDesc: "Pressione Shift+Cmd+D ou escolha 'Visualizador de Espaço em Disco...' no menu de contexto para inspecionar os maiores arquivos.",
        .helpImageTitle: "Conversor Rápido de Imagens",
        .helpImageDesc: "Clique com o botão direito em uma imagem -> 'Conversão Rápida de Imagem...' para converter formato (PNG, JPG, WEBP, HEIC), redimensionar ou cortar.",
        .helpBatchTitle: "Ferramenta de Renomeação em Lote",
        .helpBatchDesc: "Selecione vários arquivos e pressione F2 (ou Renomear) para abrir a renomeação em lote com regex, prefixo, sufixo e numeração.",
        .helpSymlinkTitle: "Criação de Links Simbólicos (Symlinks)",
        .helpSymlinkDesc: "Clique com o botão direito -> 'Criar Link Simbólico...' para gerar atalhos de sistema relativos ou absolutos.",
        .helpTemplateTitle: "Modelos de Novos Arquivos",
        .helpTemplateDesc: "Clique com o botão direito na área vazia -> 'Novo Arquivo...' para criar arquivos de texto, código ou modelos rapidamente.",
        .helpCopyContentTitle: "Copiar Conteúdo do Arquivo para a Área de Transferência",
        .helpCopyContentDesc: "Clique com o botão direito em arquivos de texto -> 'Copiar Conteúdo' para copiar o texto direto para a área de transferência.",
        .helpShredTitle: "Triturador Seguro de Arquivos",
        .helpShredDesc: "Clique com o botão direito em arquivos sensíveis -> 'Triturar Arquivo...' para sobrescrever blocos de dados antes de excluir permanentemente.",
        .helpServerTitle: "Conectar ao Servidor de Rede",
        .helpWifiShareTitle: "Compartilhamento Wi-Fi",
        .helpWifiShareDesc: "Compartilhe pastas instantaneamente na sua rede local via HTTP.",
        .helpAutoOrgTitle: "Organização Automática",
        .helpAutoOrgDesc: "Crie regras para mover arquivos recebidos automaticamente para pastas.",
        .helpServerDesc: "Pressione Cmd+K ou escolha 'Conectar ao Servidor...' no menu de opções para conectar a compartilhamentos remotos (SMB, FTP, SFTP).",
        .navSystemTitle: "Navegação, Sistema e Personalização",
        .helpUndoTitle: "Mecanismo Completo de Desfazer / Refazer",
        .helpUndoDesc: "Pressione Cmd+Z para desfazer ou Cmd+Shift+Z para refazer renomeações, criações, movimentações e exclusões.",
        .helpPreviewTitle: "Barra Lateral de Pré-visualização com Destaque de Sintaxe",
        .helpPreviewDesc: "Pressione Shift+Cmd+P ou ative Pré-visualização para ver códigos com sintaxe destacada, markdown, áudio e imagens.",
        .helpViewModeMemoryTitle: "Memória de Modo de Visualização por Diretório",
        .helpViewModeMemoryDesc: "O Wiles lembra se você prefere a visualização em Grade, Lista ou Coluna individualmente para cada pasta.",
        .helpPathBarTitle: "Barra de Caminho Interativa (Breadcrumbs)",
        .helpPathBarDesc: "Clique em qualquer segmento da barra de caminho para navegar instantaneamente. Clique no ícone de lápis para digitar caminhos.",
        .helpDragDropTitle: "Operações de Arrastar e Soltar (Drag & Drop)",
        .helpDragDropDesc: "Arraste arquivos para os favoritos da barra lateral, subpastas ou aplicativos externos. Suporta seleção por caixa no Grid e Lista.",
        .helpI18nTitle: "Sistema Multi-idioma (i18n)",
        .helpI18nDesc: "Detecção automática do idioma do sistema macOS com alteração manual (Inglês, Português, Espanhol, Francês, Alemão).",
        .helpTranslucentTitle: "Fundo Translucido e Configurações de Densidade",
        .helpTranslucentDesc: "Ajuste a transparência da barra lateral e ative o Layout de Densidade Compacta no menu de Opções.",
        .navProfilesTitle: "Perfis de Atalho de Navegação",
        .gnomeModeTitle: "Modo GNOME (Padrão)",
        .gnomeModeDesc: "• Enter: Abrir pasta ou arquivo\n• F2: Renomear item\n• Backspace: Voltar para pasta pai\n• Ctrl+H: Alternar arquivos ocultos",
        .macModeTitle: "Modo macOS Finder",
        .macModeDesc: "• Cmd+Baixo: Abrir pasta ou arquivo\n• Enter: Renomear item\n• Cmd+Cima: Voltar para pasta pai\n• Cmd+Shift+.: Alternar arquivos ocultos",
        .shortcutsCheatsheetTitle: "Lista de Atalhos de Teclado",
        .actUndo: "Desfazer Operação",
        .actRedo: "Refazer Operação",
        .actQuickLook: "Pré-visualização Quick Look",
        .actTogglePreview: "Alternar Barra de Pré-visualização",
        .actToggleTerminal: "Alternar Terminal Integrado",
        .actSearch: "Pesquisar no Diretório",
        .networkAndCloud: "REDE E NUVEM",
        .shareFolderWifi: "Compartilhar Pasta por Wi-Fi",
        .autoOrganization: "Regras de Organização Automática...",
        .noAutoOrgRules: "Nenhuma Regra",
        .noAutoOrgRulesDesc: "Os arquivos não serão movidos.",
        .addNewRule: "Adicionar Nova Regra",
        .ifFileIn: "Se arquivo em:",
        .selectFolder: "Selecionar Pasta...",
        .ruleValuePlaceholder: "Valor (ex: pdf)",
        .moveTo: "Mover para:",
        .addRule: "Adicionar Regra",
        .actDiskVisualizer: "Visualizador de Uso de Disco",
        .actConnectServer: "Conectar ao Servidor",
        .actNewFolderShortcut: "Nova Pasta",
        .actItemProperties: "Propriedades / Informações do Item",
        .actCopyShortcut: "Copiar Selecionado",
        .actCutShortcut: "Recortar Selecionado",
        .actPasteShortcut: "Colar Arquivos",
        .actMoveTrash: "Mover para o Lixo",
        .actNavBackForward: "Navegar Voltar / Avançar",
        .actParentFolder: "Pasta Pai (Superior)",
        .actRefreshShortcut: "Atualizar Diretório",
        .actToggleStatusBar: "Alternar Barra de Status",
        .fullDiskAccessPromptTitle: "Acesso Total ao Disco",
        .fullDiskAccessPromptMessage: "O Wiles precisa de Acesso Total ao Disco para navegar em todas as suas pastas sem pedir permissão repetidamente. Conceda uma vez nos Ajustes do Sistema.",
        .openSystemSettings: "Abrir Ajustes do Sistema",
        .notNow: "Agora Não"
,
        .deleteImmediately: "Excluir Imediatamente",
        .secureShred: "Triturar Arquivo com Segurança...",
        .createSymlink: "Criar Link Simbólico...",
        .compressToTarGz: "Compactar para .tar.gz",
        .hideTerminal: "Ocultar Terminal",
        .showTerminal: "Mostrar Terminal",
        .hidePreview: "Ocultar Pré-visualização",
        .showNetworkAndCloud: "Mostrar Rede e Nuvem",
        .back: "Voltar",
        .forward: "Avançar",
        .goToFolder: "Ir para a Pasta...",
        .filterImages: "Filtrar Imagens (kind:image)",
        .filterDocuments: "Filtrar Documentos (kind:doc)",
        .filterCodeFiles: "Filtrar Arquivos de Código (kind:code)",
        .filterFolders: "Filtrar Pastas (kind:folder)",
        .filterPDFs: "Filtrar PDFs (ext:pdf)",
        .filterLargeFiles: "Filtrar Arquivos Grandes >10MB (size:>10m)",
        .filterModified7Days: "Modificados nos Últimos 7 Dias (date:7d)",
        .scanningFolderSize: "Analisando tamanho da pasta...",
        .backgroundOperations: "Operações em Segundo Plano",
        .noActiveOperations: "Nenhuma operação ativa",
        .sharingActive: "Compartilhamento Ativo",
        .wifiShareNotice: "Qualquer pessoa na sua rede Wi-Fi pode acessar esta pasta visitando o endereço acima.",
        .startingServer: "Iniciando Servidor...",
        .linkType: "Tipo de Link",
        .symlinkName: "Nome do Link Simbólico",
        .noSelection: "Nenhum Item Selecionado",
        .codePreview: "Pré-visualização de Código"
,
        .openWith: "Abrir com",
        .permissionDeniedNotice: "Permissão Negada: O Wiles não pode ler o conteúdo desta pasta."
,
        .emptyFolder: "Esta Pasta está Vazia",
        .clearSearch: "Limpar Busca"
,
        .grantFullDiskAccess: "Conceder Acesso Total ao Disco (Todas as Pastas)...",
        .fullDiskAccessNotice: "Conceda Acesso Total ao Disco nos Ajustes do Sistema para acessar todas as pastas sem novos pedidos de permissão."
,
        .findDuplicates: "Buscar Arquivos Duplicados...",
        .duplicateCleanerTitle: "Limpador de Arquivos Duplicados",
        .reclaimableSpace: "Espaço Recuperável",
        .trashSelectedDuplicates: "Mover Duplicados Selecionados para o Lixo",
        .noDuplicatesFound: "Nenhum Arquivo Duplicado Encontrado",
        .batchRenameTitle: "Renomear Arquivos em Lote",
        .namingPattern: "Padrão de Nome",
        .regexReplace: "Padrão Regex",
        .emptyTrash: "Esvaziar Lixeira",
        .emptyTrashConfirm: "Tem certeza de que deseja apagar permanentemente todos os itens da Lixeira?",
        .shortcutsNav: "Navegação",
        .shortcutsFileActions: "Ações de Arquivo",
        .shortcutsSystem: "Sistema e Visualizações",
        .shortcutsOpenFolder: "Abrir Pasta Selecionada",
        .shortcutsRename: "Renomear Item Selecionado",
        .shortcutsToggleHidden: "Alternar Arquivos Ocultos",
        .shortcutsToggleOverlay: "Alternar Painel de Atalhos"
    ]
}
